/*
 * exdata.js — exercícios resolvidos (15 níveis) e propostos
 * (20 fáceis, 30 intermediários, 20 avançados).
 */
import { h } from './widgets2d.js';
import { ringSVG2 } from './sea2d.js';

const RF = (...list) => ({ node: () => h('div', { class: 'figs' }, list.map(([subs, cap]) => h('figure', { class: 'fig' }, ringSVG2({ kek: 'hyb', subs }, { scale: 30, fs: 13 }), cap ? h('figcaption', { html: cap }) : null))) });

export const SOLVED = [
  /* 1 */
  { level: 'Mecanismo geral', title: 'As etapas da SEA', q: 'Liste, em ordem, as etapas do mecanismo geral da substituição eletrofílica aromática.', think: 'Do reagente ao produto: quem ataca quem?', hint: 'São duas etapas elementares no anel, precedidas pela geração do eletrófilo.', steps: ['Geração do eletrófilo (E⁺ ou espécie fortemente polarizada) pelos reagentes/catalisador.', 'Ataque do sistema π ao E (etapa lenta, ET₁).', 'Complexo σ (íon arênio): carbono sp³, carga + deslocalizada, aromaticidade perdida.', 'Desprotonação do carbono sp³ por uma base (ET₂, rápida).', 'Restauração da aromaticidade: Ar–E + H⁺.'], answer: 'gerar E⁺ → ataque π → complexo σ → desprotonação → produto aromático.' },
  { level: 'Mecanismo geral', title: 'Quem é o nucleófilo?', q: 'Na SEA, qual espécie atua como nucleófilo e por quê?', think: 'Onde estão os elétrons mais disponíveis do benzeno?', hint: 'Pense na nuvem π.', steps: ['O <b>anel aromático</b> é o nucleófilo: seus 6 elétrons π ficam acima e abaixo do plano, acessíveis ao eletrófilo.', 'Ele é um nucleófilo fraco (atacar significa perder a aromaticidade temporariamente): por isso precisa de eletrófilos fortes, gerados com catalisadores.'], answer: 'O sistema π do anel.' },
  { level: 'Mecanismo geral', title: 'Por que sai H⁺?', q: 'Por que, no complexo σ, o grupo removido é o H⁺ e não o E recém-ligado?', think: 'O que restaura a aromaticidade?', hint: 'Compare as duas opções de saída.', steps: ['A saída de E⁺ simplesmente desfaria a reação (volta aos reagentes).', 'A perda de H⁺ leva ao produto substituído aromático, muito mais estável.', 'Na prática, a perda de H⁺ é rápida; para eletrófilos que formam ligações fracas (ex.: SO₃), a reversão também é possível — por isso a sulfonação é reversível.'], answer: 'A perda de H⁺ leva ao produto aromático (e E⁺ voltaria aos reagentes).' },
  /* 2 */
  { level: 'Complexo σ', title: 'Hibridização no complexo σ', q: 'Qual a hibridização do carbono atacado no complexo σ? Ele é aromático?', think: 'Conte as ligações desse carbono.', hint: 'Quatro ligações σ.', steps: ['O carbono atacado liga-se a dois C do anel, ao H e ao E: quatro ligações σ → <b>≈ sp³</b>.', 'Sem orbital p, ele interrompe o ciclo de orbitais p.', 'Restam 5 orbitais p com 4 elétrons e carga +: sistema pentadienila, estabilizado por ressonância mas <b>não aromático</b>.'], answer: 'sp³; não aromático.' },
  { level: 'Complexo σ', title: 'Onde fica a carga?', q: 'Em quais posições (em relação ao carbono sp³) aparece a carga positiva nas formas de ressonância do íon arênio?', think: 'Mova os pares π vizinhos à carga.', hint: 'São três formas.', steps: ['Forma 1: + no carbono adjacente (orto ao C sp³).', 'Forma 2: + no carbono para ao C sp³.', 'Forma 3: + no outro carbono orto.', 'Nunca no meta: são formas canônicas de <b>um único</b> intermediário.'], answer: 'orto, para e orto (nunca meta).' },
  { level: 'Complexo σ', title: 'Nomes', q: 'Que outros nomes recebe o complexo σ?', think: 'Íon de…', hint: 'Um nome homenageia um químico.', steps: ['Íon arênio (ou arenônio).', 'Intermediário de Wheland.', '“σ” porque o eletrófilo está ligado por uma ligação σ a um carbono do anel.'], answer: 'íon arênio / arenônio; intermediário de Wheland.' },
  /* 3 */
  { level: 'Perfil energético', title: 'Etapa lenta', q: 'Por que, em geral, a formação do complexo σ é a etapa lenta?', think: 'O que se perde nessa etapa?', hint: 'Estabilização aromática.', steps: ['Para formar o complexo σ o anel perde temporariamente a estabilização aromática (~150 kJ/mol no benzeno).', 'O ET₁ se parece com o complexo σ (postulado de Hammond): ambos são altos em energia.', 'Na etapa seguinte a aromaticidade é recuperada: barreira pequena, etapa rápida.'], answer: 'Porque exige perder a aromaticidade (barreira alta).' },
  { level: 'Perfil energético', title: 'Efeito isotópico', q: 'Na nitração do benzeno e do C₆D₆ as velocidades são quase iguais (kH/kD ≈ 1). O que isso indica?', think: 'Em que etapa a ligação C–H (ou C–D) se rompe?', hint: 'Se ela fosse rompida na etapa lenta…', steps: ['A ligação C–H só se rompe na etapa 2 (desprotonação).', 'Se essa etapa fosse lenta, trocar H por D diminuiria a velocidade (kH/kD > 1).', 'Como kH/kD ≈ 1, a etapa lenta é a 1 (ataque e formação do complexo σ).'], answer: 'A ruptura C–H não é a etapa lenta.' },
  /* 4 */
  { level: 'Halogenação', title: 'Papel do FeBr₃', q: 'Por que a bromação do benzeno exige FeBr₃, enquanto alcenos reagem com Br₂ sem catalisador?', think: 'Compare os nucleófilos.', hint: 'O benzeno é um nucleófilo fraco.', steps: ['Alcenos: π localizada, sem estabilização especial — reagem com Br₂ diretamente.', 'Benzeno: atacar custa a aromaticidade; o Br₂ sozinho não é eletrófilo suficiente.', 'FeBr₃ (ácido de Lewis) recebe um par do Br₂: Br–Br⁺–Fe⁻Br₃. A ligação Br–Br fica muito polarizada e o Br terminal, fortemente eletrofílico.', 'Representação simplificada: não há Br⁺ livre em solução.'], answer: 'Ativa (polariza) o Br₂, gerando uma espécie bromante forte.' },
  { level: 'Halogenação', title: 'Regeneração do catalisador', q: 'Escreva o que acontece com o FeBr₃ ao final da bromação.', think: 'Quem é a base que remove H⁺?', hint: 'FeBr₄⁻.', steps: ['Após o ataque, forma-se FeBr₄⁻.', 'FeBr₄⁻ atua como base: remove H⁺ do complexo σ.', 'Produtos: bromobenzeno + HBr + FeBr₃ (regenerado): o FeBr₃ é catalisador.'], answer: 'FeBr₄⁻ + H⁺ → HBr + FeBr₃.' },
  { level: 'Halogenação', title: 'Cloração do tolueno', q: 'Preveja os produtos principais de tolueno + Cl₂/FeCl₃.', think: 'CH₃ é ativador fraco, orto/para.', hint: 'Duas posições orto, uma para.', steps: ['–CH₃: ativador fraco (hiperconjugação/+I), orto/para.', 'Formam-se o-clorotolueno e p-clorotolueno (meta em pequena quantidade).', 'A proporção depende das condições; o grupo metila é pequeno, então orto é significativo.'], solFig: RF([{ 0: 'CH3', 1: 'Cl' }, 'orto'], [{ 0: 'CH3', 3: 'Cl' }, 'para']), answer: 'o- e p-clorotolueno.' },
  /* 5 */
  { level: 'Nitração', title: 'Formação do NO₂⁺', q: 'Mostre como o íon nitrônio é formado a partir de HNO₃ e H₂SO₄.', think: 'Quem é o ácido mais forte?', hint: 'Protonação do –OH, saída de água.', steps: ['H₂SO₄ protona o grupo –OH do HNO₃: H₂O⁺–NO₂.', 'Sai H₂O (bom grupo de saída): O=N⁺=O.', 'Global: HNO₃ + 2 H₂SO₄ ⇌ NO₂⁺ + H₃O⁺ + 2 HSO₄⁻.', 'NO₂⁺ é linear (N sp), isoeletrônico do CO₂.'], answer: 'NO₂⁺ (por protonação do HNO₃ e perda de H₂O).' },
  { level: 'Nitração', title: 'Dinitração', q: 'Ao nitrar o nitrobenzeno (condições mais drásticas), qual produto principal se forma?', think: 'NO₂ é desativador e diretor…', hint: 'meta.', steps: ['–NO₂: desativador forte, meta diretor.', 'A segunda nitração é bem mais lenta (exige temperatura maior/ácido fumegante).', 'Produto principal: 1,3-dinitrobenzeno (m-dinitrobenzeno).'], solFig: RF([{ 0: 'NO2', 2: 'NO2' }, 'm-dinitrobenzeno']), answer: '1,3-dinitrobenzeno.' },
  /* 6 */
  { level: 'Sulfonação', title: 'Reversibilidade', q: 'Como se pode remover um grupo –SO₃H de um anel aromático?', think: 'A sulfonação é um equilíbrio.', hint: 'Desloque o equilíbrio.', steps: ['ArSO₃H + H₂O ⇌ ArH + H₂SO₄.', 'Ácido diluído (muita água) e aquecimento deslocam para a esquerda: dessulfonação.', 'Mecanismo: H⁺ ataca o carbono ipso (SEA com o próton como eletrófilo) e sai SO₃.'], answer: 'Aquecendo com ácido diluído (dessulfonação).' },
  { level: 'Sulfonação', title: 'Grupo bloqueador', q: 'Como obter o-bromotolueno com boa seletividade a partir do tolueno?', think: 'O problema é o isômero para.', hint: 'Ocupe a posição para temporariamente.', steps: ['Sulfonar o tolueno: –SO₃H entra em para (volumoso; para favorecido).', 'Bromar: CH₃ (o/p) e SO₃H (meta) concordam na posição orto ao CH₃.', 'Dessulfonar (H₃O⁺, Δ): o-bromotolueno.'], solFig: RF([{ 0: 'CH3', 3: 'SO3H' }, '1'], [{ 0: 'CH3', 1: 'Br', 3: 'SO3H' }, '2'], [{ 0: 'CH3', 1: 'Br' }, '3']), answer: 'sulfonação → bromação → dessulfonação.' },
  /* 7 */
  { level: 'Friedel–Crafts: alquilação', title: 'Rearranjo', q: 'Benzeno + 1-cloropropano/AlCl₃ fornece principalmente isopropilbenzeno. Explique.', think: 'Qual carbocátion é mais estável?', hint: 'Migração de hidreto.', steps: ['AlCl₃ ativa o haleto: espécie com caráter de carbocátion primário.', 'Migração 1,2 de hidreto → carbocátion secundário (CH₃)₂CH⁺, mais estável.', 'O anel ataca o eletrófilo rearranjado: isopropilbenzeno (cumeno) majoritário.'], solFig: RF([{ 0: 'CH(CH₃)₂' }, 'majoritário']), answer: 'Rearranjo por migração de hidreto.' },
  { level: 'Friedel–Crafts: alquilação', title: 'Polialquilação', q: 'Por que a alquilação de Friedel–Crafts tende à polialquilação? Como minimizar?', think: 'O produto é mais ou menos reativo que o benzeno?', hint: 'Alquila é ativador.', steps: ['O grupo alquila introduzido ativa o anel (+I/hiperconjugação).', 'O produto monoalquilado reage mais rápido que o benzeno e compete pelo eletrófilo.', 'Usa-se grande excesso do aromático para favorecer a monoalquilação.'], answer: 'O produto é mais reativo; usar excesso de benzeno.' },
  { level: 'Friedel–Crafts: alquilação', title: 'terc-Butilação', q: 'Benzeno + (CH₃)₃C–Cl/AlCl₃: há rearranjo? Qual o produto?', think: 'O carbocátion já é terciário.', hint: 'Não há cátion mais estável acessível.', steps: ['Forma-se o cátion terc-butila (terciário).', 'Não há rearranjo para um cátion mais estável.', 'Produto: terc-butilbenzeno (grupo volumoso: dialquilação ocorre preferencialmente em para).'], solFig: RF([{ 0: 'tBu' }, 'terc-butilbenzeno']), answer: 'terc-butilbenzeno, sem rearranjo.' },
  /* 8 */
  { level: 'Friedel–Crafts: acilação', title: 'Íon acílio', q: 'Escreva as formas de ressonância do íon acílio e explique por que ele não rearranja.', think: 'R–C≡O⁺.', hint: 'O O doa um par.', steps: ['R–C≡O⁺ ↔ R–C⁺=O.', 'A forma com tripla (octetos completos) é importante: o íon é muito estabilizado.', 'Não há carbocátion vizinho mais estável para onde migrar: sem rearranjo.'], answer: 'R–C≡O⁺ ↔ R–C⁺=O; estabilizado por ressonância.' },
  { level: 'Friedel–Crafts: acilação', title: 'Sem poliacilação', q: 'Por que a acilação, ao contrário da alquilação, para na monossubstituição?', think: 'Que tipo de grupo é –COR?', hint: 'Retirador.', steps: ['–COR é retirador (−I, −R): desativa o anel.', 'A cetona formada é menos reativa que o substrato; além disso, complexa-se ao AlCl₃.', 'Resultado: monoacilação.'], answer: 'O grupo acila desativa o anel.' },
  { level: 'Friedel–Crafts: acilação', title: 'Propilbenzeno', q: 'Proponha uma síntese do propilbenzeno a partir do benzeno sem rearranjo.', think: 'Acilação não rearranja.', hint: 'Depois reduza a C=O.', steps: ['Acilação: CH₃CH₂COCl/AlCl₃ → propiofenona (C₆H₅COCH₂CH₃).', 'Redução da carbonila: Zn(Hg)/HCl (Clemmensen) ou H₂NNH₂/KOH (Wolff–Kishner).', 'Produto: propilbenzeno linear.'], answer: 'acilação + redução de Clemmensen/Wolff–Kishner.' },
  /* 9 */
  { level: 'Ativadores e desativadores', title: 'Ordem de reatividade', q: 'Ordene em SEA (mais rápido → mais lento): benzeno, anisol, nitrobenzeno, clorobenzeno, tolueno.', think: 'Classifique cada grupo.', hint: 'OCH₃ forte ativador; CH₃ fraco; Cl desativador fraco; NO₂ forte.', steps: ['anisol (+R forte) > tolueno (+I/hiperconj.) > benzeno > clorobenzeno (−I > +R) > nitrobenzeno (−I, −R fortes).'], answer: 'anisol > tolueno > benzeno > clorobenzeno > nitrobenzeno.' },
  { level: 'Ativadores e desativadores', title: 'Anisol × benzeno', q: 'Explique por que o anisol reage muito mais rápido que o benzeno em SEA, apesar de o O ser eletronegativo (−I).', think: 'Dois efeitos competem.', hint: 'Ressonância domina.', steps: ['−I: o O retira densidade pelas ligações σ.', '+R: um par do O conjuga com o anel e pode estabilizar diretamente o complexo σ (forma O⁺=C).', 'Para O e N ligados ao anel, +R domina: grupo fortemente ativador.'], answer: 'O +R do oxigênio supera o −I.' },
  /* 10 */
  { level: 'Orto, meta, para', title: 'Nitração do tolueno', q: 'Preveja os produtos de tolueno + HNO₃/H₂SO₄.', think: 'CH₃: ativador fraco, o/p.', hint: 'Mistura.', steps: ['–CH₃ ativa fracamente e dirige orto/para (no ataque o/p, uma forma tem + em carbono terciário vizinho ao CH₃).', 'Produtos principais: o-nitrotolueno e p-nitrotolueno (meta, poucos %).', 'Valores típicos aproximados: ~58% o, ~4% m, ~38% p.'], solFig: RF([{ 0: 'CH3', 1: 'NO2' }, 'orto'], [{ 0: 'CH3', 3: 'NO2' }, 'para']), answer: 'o- e p-nitrotolueno.' },
  { level: 'Orto, meta, para', title: 'Bromação do nitrobenzeno', q: 'Nitrobenzeno + Br₂/FeBr₃: produto principal e velocidade relativa ao benzeno?', think: 'NO₂ retira por indução e ressonância.', hint: 'Analise os complexos σ.', steps: ['–NO₂ é fortemente retirador: anel desativado, reação mais lenta (condições mais drásticas).', 'No ataque o/p, uma forma tem + no carbono ligado ao N⁺: cargas positivas adjacentes, muito desfavorável.', 'No ataque meta isso não ocorre: meta é relativamente favorecido.', 'Produto: m-bromonitrobenzeno.'], solFig: RF([{ 0: 'NO2', 2: 'Br' }, 'meta']), answer: 'm-bromonitrobenzeno; mais lento que o benzeno.' },
  { level: 'Orto, meta, para', title: 'Acetofenona', q: 'Preveja o produto da nitração da acetofenona.', think: 'C=O conjugado com o anel.', hint: '−R.', steps: ['–COCH₃: −I e −R (carbono carbonílico δ+).', 'Ataques o/p colocariam + no carbono ligado à C=O: desfavorável.', 'Produto principal: m-nitroacetofenona.'], solFig: RF([{ 0: 'COCH3', 2: 'NO2' }, 'meta']), answer: 'm-nitroacetofenona.' },
  /* 11 */
  { level: 'Ressonância de substituintes', title: 'Anisol', q: 'Desenhe (descreva) as formas de ressonância do anisol que mostram doação do par do O ao anel.', think: 'O par do O forma O⁺=C.', hint: 'Cargas − em o e p.', steps: ['O par do O forma ligação π com C1 (O⁺=C1).', 'Os pares π do anel se deslocam: carga − em C2, C4 ou C6 (orto, para, orto).', 'Conclusão: o anel fica mais rico em elétrons, sobretudo em orto e para.'], answer: 'Três formas com − em orto, para, orto.' },
  { level: 'Ressonância de substituintes', title: 'Benzaldeído', q: 'Que formas de ressonância mostram o grupo –CHO retirando densidade do anel?', think: 'O oxigênio da C=O recebe o par.', hint: '+ em o e p.', steps: ['Um par π do anel forma C1=C(H)–O⁻.', 'Surge carga + em C2, C4 ou C6 (orto, para).', 'O anel fica mais pobre, sobretudo em orto/para — e os complexos σ o/p ficam desfavorecidos.'], answer: 'Formas com O⁻ e + no anel em orto/para.' },
  /* 12 */
  { level: 'Halogênios', title: 'Nitração do clorobenzeno', q: '(1) O anel está ativado ou desativado? (2) Orientação? (3) Produtos principais?', think: 'Halogênio: −I forte, +R fraco.', hint: 'Efeitos diferentes para velocidade e orientação.', steps: ['(1) Desativado (−I domina): mais lento que o benzeno.', '(2) Orto/para: no ataque o/p o par do Cl permite uma forma Cl⁺=C.', '(3) p-cloronitrobenzeno (majoritário) e o-cloronitrobenzeno; meta muito pouco.'], solFig: RF([{ 0: 'Cl', 3: 'NO2' }, 'para (maj.)'], [{ 0: 'Cl', 1: 'NO2' }, 'orto']), answer: 'desativado; orto/para; p > o.' },
  { level: 'Halogênios', title: 'A aparente contradição', q: 'Como um grupo pode ser desativador e, ao mesmo tempo, orto/para diretor?', think: 'Velocidade × orientação.', hint: 'Indução afeta todos os caminhos; ressonância só alguns.', steps: ['O −I do halogênio eleva a energia de <b>todos</b> os complexos σ: reação mais lenta que no benzeno.', 'O +R só ajuda quando a carga + chega ao carbono ligado ao halogênio: ataques orto/para.', 'Assim, entre caminhos todos desfavorecidos, orto/para são os menos desfavorecidos.'], answer: 'O −I controla a velocidade; o +R controla a orientação.' },
  /* 13 */
  { level: 'Regiosseletividade', title: 'terc-Butilbenzeno', q: 'Na nitração do terc-butilbenzeno, por que o produto para é fortemente majoritário?', think: 'Eletrônica + estérica.', hint: 'Grupo muito volumoso.', steps: ['Eletronicamente: alquila, orto/para.', 'Estericamente: o grupo terc-butila bloqueia a aproximação em orto.', 'Resultado típico: para ≫ orto (~75% para).'], solFig: RF([{ 0: 'tBu', 3: 'NO2' }, 'para']), answer: 'Impedimento estérico em orto.' },
  { level: 'Regiosseletividade', title: 'Bromação do anisol', q: 'Anisol + Br₂ reage até sem catalisador. Quais produtos predominam?', think: 'Anel muito ativado, o/p.', hint: 'para costuma predominar.', steps: ['–OCH₃: forte ativador, orto/para (contribuinte extra O⁺=C).', 'Anel tão ativado que a bromação ocorre mesmo sem FeBr₃.', 'Predominam p-bromoanisol (maj.) e o-bromoanisol.'], solFig: RF([{ 0: 'OCH3', 3: 'Br' }, 'para (maj.)'], [{ 0: 'OCH3', 1: 'Br' }, 'orto']), answer: 'p- (maj.) e o-bromoanisol.' },
  /* 14 */
  { level: 'Dois substituintes', title: '4-nitrotolueno', q: 'Onde ocorre uma nova nitração no 4-nitrotolueno?', think: 'CH₃ o/p; NO₂ meta.', hint: 'Diretores concordantes.', steps: ['CH₃ (C1) dirige para C2/C6 (orto; para ocupado).', 'NO₂ (C4) dirige para C2/C6 (meta a ele).', 'Concordam: C2 → 2,4-dinitrotolueno.'], solFig: RF([{ 0: 'CH3', 1: 'NO2', 3: 'NO2' }, '2,4-dinitrotolueno']), answer: 'C2 (orto ao CH₃, meta ao NO₂).' },
  { level: 'Dois substituintes', title: '4-metilanisol', q: 'Onde ocorre a bromação do 4-metilanisol?', think: 'Conflito: OCH₃ × CH₃.', hint: 'O mais ativador decide.', steps: ['OCH₃ (forte ativador) favorece C2/C6 (orto a ele).', 'CH₃ (fraco) favoreceria C3/C5.', 'Prevalece o grupo mais ativador: bromação em C2 (orto ao OCH₃).'], solFig: RF([{ 0: 'OCH3', 1: 'Br', 3: 'CH3' }, 'produto']), answer: 'Orto ao OCH₃.' },
  { level: 'Dois substituintes', title: 'm-Xileno', q: 'Qual posição do m-xileno (1,3-dimetilbenzeno) é favorecida na SEA? Por que C2 é minoritária?', think: 'Os dois CH₃ concordam em várias posições.', hint: 'Estérica.', steps: ['C4/C6: orto a um CH₃ e para ao outro — ativadas duplamente.', 'C2: orto a ambos, mas entre dois grupos — congestionada.', 'C5: meta a ambos — desfavorecida.', 'Produto principal: substituição em C4.'], answer: 'C4 (C2 sofre impedimento estérico).' },
  /* 15 */
  { level: 'Síntese aromática simples', title: 'm-Bromonitrobenzeno', q: 'Proponha a síntese do m-bromonitrobenzeno a partir do benzeno.', think: 'Qual grupo dirige meta?', hint: 'A ordem importa.', steps: ['1. Nitração (HNO₃/H₂SO₄) → nitrobenzeno.', '2. Bromação (Br₂/FeBr₃): NO₂ dirige meta → m-bromonitrobenzeno.', 'Na ordem inversa, o Br dirigiria o/p.'], solFig: RF([{ 0: 'NO2', 2: 'Br' }, 'alvo']), answer: 'nitração → bromação.' },
  { level: 'Síntese aromática simples', title: 'p-Bromonitrobenzeno', q: 'E o p-bromonitrobenzeno?', think: 'Agora queremos para.', hint: 'Br primeiro.', steps: ['1. Bromação → bromobenzeno (o/p diretor).', '2. Nitração → mistura o/p; separa-se o isômero para (majoritário).'], solFig: RF([{ 0: 'Br', 3: 'NO2' }, 'alvo']), answer: 'bromação → nitração (separar o para).' },
  { level: 'Síntese aromática simples', title: 'm-Nitroacetofenona', q: 'Por que, para obter m-nitroacetofenona, a acilação deve vir antes da nitração?', think: 'Friedel–Crafts e anéis desativados.', hint: 'Nitrobenzeno não sofre FC.', steps: ['Acilar primeiro: acetofenona; depois nitrar → meta (–COCH₃ dirige meta).', 'Na ordem inversa, a Friedel–Crafts falharia no nitrobenzeno (anel fortemente desativado).'], solFig: RF([{ 0: 'COCH3', 2: 'NO2' }, 'alvo']), answer: 'acilação → nitração.' },
];

/* ===================================================================
 * Propostos
 * =================================================================== */
const mc = (title, q, o, e, fig) => ({ title, type: 'mc', q, o, a: 0, e, fig });
const tf = (title, items, e) => ({ title, type: 'tf', q: 'Marque V ou F:', items, e });
const dnd = (title, q, pairs, e) => ({ title, type: 'dnd', q, pairs, e });
const err = (title, claim, o, e) => mc('Detecte o erro · ' + title, `Afirmação de um estudante: <i>“${claim}”</i>. Qual é o erro?`, o, e);
const F = (subs) => RF([subs]);

export const PROPOSED = {
  easy: [
    mc('Equação geral', 'A equação geral da SEA é:', ['Ar–H + E⁺ → Ar–E + H⁺', 'Ar–H + Nu⁻ → Ar–Nu + H⁻', 'Ar–H + E⁺ → Ar(H)(E)⁺ (produto final)', 'Ar + E₂ → Ar–E₂'], 'Um H é substituído por E.'),
    mc('Nucleófilo', 'Na SEA, o nucleófilo é:', ['o sistema π do anel', 'o eletrófilo', 'o catalisador', 'o H⁺'], 'Nuvem π.'),
    mc('Intermediário', 'O intermediário da SEA chama-se:', ['complexo σ (íon arênio)', 'carbânion benzílico', 'radical fenila', 'benzino'], 'Wheland.'),
    mc('Aromaticidade', 'No complexo σ, a aromaticidade está:', ['perdida temporariamente', 'intacta', 'aumentada', 'perdida definitivamente'], 'É restaurada na desprotonação.'),
    mc('Eletrófilo da nitração', 'Qual é o eletrófilo efetivo da nitração?', ['NO₂⁺', 'NO₃⁻', 'HNO₃', 'NO₂⁻'], 'Íon nitrônio.'),
    mc('Halogenação', 'Na bromação do benzeno, o FeBr₃ atua como:', ['ácido de Lewis que ativa o Br₂', 'base', 'agente redutor', 'solvente'], 'Polariza Br–Br.'),
    mc('Sulfonação', 'O produto da sulfonação do benzeno é:', ['ácido benzenossulfônico', 'fenol', 'tiofenol', 'benzeno-sulfeto'], 'Ar–SO₃H.'),
    mc('Acilação', 'O eletrófilo da acilação de Friedel–Crafts é:', ['o íon acílio R–C≡O⁺', 'R⁻', 'RCOO⁻', 'AlCl₄⁻'], 'Estabilizado por ressonância.'),
    mc('Ativação', 'Qual reage MAIS rápido em SEA?', ['anisol', 'benzeno', 'nitrobenzeno', 'clorobenzeno'], 'OCH₃: forte ativador.'),
    mc('Ativação', 'Benzeno × tolueno: qual reage mais rápido?', ['tolueno', 'benzeno', 'iguais', 'nenhum reage'], 'CH₃ ativa fracamente.'),
    mc('Desativação', 'Benzeno × nitrobenzeno: qual reage mais rápido?', ['benzeno', 'nitrobenzeno', 'iguais', 'depende só da temperatura'], 'NO₂ desativa fortemente.'),
    mc('Orientação', '–NO₂ é diretor:', ['meta', 'orto/para', 'só orto', 'só para'], 'Retirador forte.'),
    mc('Orientação', '–CH₃ é diretor:', ['orto/para', 'meta', 'ipso', 'não orienta'], 'Ativador fraco.'),
    mc('Orientação', '–OH é:', ['forte ativador, orto/para', 'desativador, meta', 'desativador, orto/para', 'ativador, meta'], 'Par do O doa.'),
    mc('Halogênios', '–Cl é:', ['desativador, orto/para', 'ativador, orto/para', 'desativador, meta', 'ativador, meta'], '−I > +R.'),
    mc('Regiosseletividade', 'Tolueno + HNO₃/H₂SO₄ fornece principalmente:', ['o- e p-nitrotolueno', 'm-nitrotolueno', 'só o-nitrotolueno', 'nitrobenzeno + metano'], 'o/p.', F({ 0: 'CH3' })),
    mc('Regiosseletividade', 'Nitrobenzeno + Br₂/FeBr₃ fornece principalmente:', ['m-bromonitrobenzeno', 'p-bromonitrobenzeno', 'o-bromonitrobenzeno', 'bromobenzeno'], 'meta.', F({ 0: 'NO2' })),
    tf('Conceitos', [['A formação do complexo σ costuma ser a etapa lenta.', 'V'], ['O complexo σ é aromático.', 'F'], ['A base remove o H do carbono sp³.', 'V'], ['A sulfonação é reversível.', 'V']], 'Revisar módulos 4–9.'),
    dnd('Reação → eletrófilo', 'Associe cada reação ao seu eletrófilo efetivo:', [['nitração', 'NO₂⁺'], ['acilação', 'R–C≡O⁺'], ['bromação', 'Br₂···FeBr₃'], ['sulfonação', 'SO₃'], ['alquilação (2ª/3ª)', 'R⁺']], 'Eletrófilos gerados pelos reagentes.'),
    dnd('Substituinte → orientação', 'Associe cada substituinte à orientação:', [['–OCH₃', 'orto/para'], ['–NO₂', 'meta'], ['–Br', 'orto/para'], ['–CN', 'meta'], ['–CH₃', 'orto/para'], ['–CHO', 'meta']], 'Doadores e halogênios: o/p; retiradores: meta.'),
  ],
  mid: [
    mc('Br₂ sozinho', 'Por que o Br₂ sozinho não bromata o benzeno?', ['é eletrófilo fraco demais para um anel que perderia a aromaticidade', 'o benzeno não tem elétrons π', 'Br₂ é nucleófilo', 'forma radicais'], 'Precisa de ácido de Lewis.'),
    mc('Representação', 'Sobre “Br⁺” na bromação:', ['não existe Br⁺ livre; a espécie reativa é o complexo Br–Br–FeBr₃ polarizado', 'Br⁺ livre é o eletrófilo comum', 'Br⁺ é gerado por luz', 'Br⁺ é uma base'], 'Representação simplificada.'),
    mc('Nitrônio', 'Geometria do NO₂⁺:', ['linear (180°)', 'angular (120°)', 'trigonal planar', 'tetraédrica'], 'N sp; isoeletrônico do CO₂.'),
    mc('Papel do H₂SO₄', 'Na nitração, o H₂SO₄:', ['protona o HNO₃, que perde H₂O formando NO₂⁺', 'é o eletrófilo', 'é oxidado', 'é a base que forma o produto final irreversivelmente'], 'Ácido mais forte.'),
    mc('Perfil', 'No perfil de energia da SEA, o complexo σ é:', ['um intermediário (mínimo local)', 'um estado de transição', 'o produto', 'o reagente'], 'Entre ET₁ e ET₂.'),
    mc('Energia', 'A perda de H⁺ (etapa 2) é rápida porque:', ['restaura a aromaticidade', 'forma um carbocátion', 'é endotérmica', 'quebra uma ligação C–C'], 'Força motriz.'),
    mc('kH/kD', 'kH/kD ≈ 1 na nitração indica que:', ['a ruptura C–H não ocorre na etapa lenta', 'a ruptura C–H é a etapa lenta', 'não há intermediário', 'o mecanismo é radicalar'], 'Etapa 1 é a lenta.'),
    mc('Rearranjo', 'Benzeno + 1-cloropropano/AlCl₃ dá principalmente:', ['isopropilbenzeno', 'propilbenzeno', 'tolueno', 'clorobenzeno'], 'Migração de hidreto.'),
    mc('Rearranjo', 'Qual eletrófilo efetivo se forma a partir de 1-cloro-2-metilpropano/AlCl₃?', ['cátion terc-butila (após migração de hidreto)', 'cátion isobutila primário estável', 'cátion metila', 'íon acílio'], '1° → 3°.'),
    mc('Polialquilação', 'Para minimizar a polialquilação usa-se:', ['excesso do composto aromático', 'excesso do haleto', 'mais AlCl₃', 'temperatura alta'], 'O produto é mais reativo.'),
    mc('Acilação', 'Por que se usa ≥ 1 equivalente de AlCl₃ na acilação?', ['a cetona produto complexa o AlCl₃', 'o AlCl₃ é consumido como eletrófilo', 'para gerar mais rearranjos', 'para evitar a hidrólise'], 'Workup libera a cetona.'),
    mc('FC + redução', 'Rota para propilbenzeno sem rearranjo:', ['acilação com CH₃CH₂COCl e redução de Clemmensen', 'alquilação com 1-cloropropano', 'sulfonação e dessulfonação', 'nitração e redução'], 'Acilação não rearranja.'),
    mc('Ressonância', 'No anisol, as formas de ressonância colocam carga negativa em:', ['orto e para', 'meta', 'só no O', 'ipso'], 'O⁺=C.'),
    mc('Ressonância', 'No nitrobenzeno, as formas de ressonância colocam carga positiva no anel em:', ['orto e para', 'meta', 'só no N', 'em nenhuma posição'], '−R.'),
    mc('Indução', '–CF₃ é desativador porque:', ['retira por indução (três F)', 'doa por ressonância', 'tem par isolado', 'é volumoso'], 'Sem pares: só −I.'),
    mc('Halogênio', 'No clorobenzeno, o +R fraco do Cl:', ['estabiliza seletivamente os complexos σ orto/para', 'ativa o anel', 'dirige meta', 'não existe'], 'Orientação, não velocidade.'),
    mc('Ácido benzoico', 'A nitração do ácido benzoico dá principalmente:', ['ácido m-nitrobenzoico', 'ácido p-nitrobenzoico', 'ácido o-nitrobenzoico', 'nitrobenzeno'], '–COOH meta.', F({ 0: 'COOH' })),
    mc('Benzaldeído', 'Bromação do benzaldeído (Br₂/FeBr₃):', ['m-bromobenzaldeído', 'p-bromobenzaldeído', 'o-bromobenzaldeído', 'não reage'], '–CHO meta.', F({ 0: 'CHO' })),
    mc('Acetanilida', 'Nitração da acetanilida:', ['principalmente p-nitroacetanilida', 'principalmente meta', 'só orto', 'não reage'], 'Grupo volumoso o/p.', F({ 0: 'NHCOCH3' })),
    mc('Estérico', 'Para um mesmo diretor o/p, aumentar o volume do grupo:', ['aumenta a fração para', 'aumenta a fração orto', 'muda para meta', 'não altera'], 'Impedimento em orto.'),
    mc('FC funciona?', 'Benzeno + CH₃COCl/AlCl₃:', ['funciona: acetofenona', 'não funciona', 'dá tolueno', 'dá ácido benzoico'], 'Acilação clássica.'),
    mc('FC funciona?', 'Nitrobenzeno + CH₃Cl/AlCl₃:', ['não funciona bem (anel fortemente desativado)', 'dá m-nitrotolueno com bom rendimento', 'dá p-nitrotolueno', 'dá anilina'], 'FC exige anel não desativado.'),
    mc('FC funciona?', 'Anilina + CH₃COCl/AlCl₃ (condições clássicas):', ['falha: o NH₂ complexa o AlCl₃ (e reage com o cloreto de acila no N)', 'dá p-aminoacetofenona limpa', 'dá m-aminoacetofenona', 'dá acetanilida apenas por SEA'], 'N básico.'),
    mc('Dois grupos', '4-nitrotolueno + HNO₃/H₂SO₄: posição favorecida?', ['C2 (orto ao CH₃, meta ao NO₂)', 'C3 (orto ao NO₂)', 'C1', 'nenhuma'], 'Concordantes.', F({ 0: 'CH3', 3: 'NO2' })),
    mc('Dois grupos', '1,3-dinitrobenzeno: nova SEA (difícil) ocorreria em:', ['C5 (meta a ambos)', 'C2', 'C4', 'C1'], 'Meta a ambos.', F({ 0: 'NO2', 2: 'NO2' })),
    tf('Friedel–Crafts', [['A acilação não sofre rearranjo do íon acílio.', 'V'], ['A alquilação nunca rearranja.', 'F'], ['O grupo acila ativa o anel.', 'F'], ['Haletos de vinila e arila não servem como fonte de carbocátion na FC.', 'V']], 'Ver módulos 10–11.'),
    tf('Substituintes', [['Todo diretor orto/para é ativador.', 'F'], ['–NH₃⁺ é desativador meta.', 'V'], ['–OCOCH₃ é ativador moderado.', 'V'], ['–CN é ativador.', 'F']], 'Halogênios: desativadores o/p.'),
    dnd('Substituinte → efeito', 'Classifique:', [['–NH₂', 'ativador'], ['–OCH₃', 'ativador'], ['–Cl', 'desativador'], ['–NO₂', 'desativador'], ['–CH₃', 'ativador'], ['–COOH', 'desativador']], 'Velocidade relativa ao benzeno.'),
    dnd('Reagentes → reação', 'Associe:', [['HNO₃/H₂SO₄', 'nitração'], ['SO₃/H₂SO₄', 'sulfonação'], ['Cl₂/FeCl₃', 'cloração'], ['RCOCl/AlCl₃', 'acilação'], ['R–Cl/AlCl₃', 'alquilação']], 'Reagentes típicos.'),
    { title: 'Ordem de reatividade', type: 'order', q: 'Ordene do MAIS reativo ao MENOS reativo em SEA:', items: [['a', 'anilina'], ['t', 'tolueno'], ['b', 'benzeno'], ['c', 'clorobenzeno'], ['n', 'nitrobenzeno']].map(([id, label]) => ({ id, label })), correct: ['a', 't', 'b', 'c', 'n'], top: 'mais rápido', bottom: 'mais lento', explain: 'NH₂ ≫ CH₃ > H > Cl > NO₂.', e: 'NH₂ ≫ CH₃ > H > Cl > NO₂ (qualitativo).' },
  ],
  hard: [
    err('nitração', 'Na nitração, o eletrófilo é o íon nitrato, NO₃⁻.', ['NO₃⁻ é rico em elétrons; o eletrófilo é NO₂⁺', 'o eletrófilo é o H₂SO₄', 'o eletrófilo é o benzeno', 'não há erro'], 'NO₂⁺.'),
    err('setas', 'A primeira seta parte do E⁺ e vai até o anel.', ['setas indicam fluxo de elétrons: partem do par π (nucleófilo) para o E⁺', 'a seta deve partir do H', 'a seta parte do catalisador', 'não há erro'], 'Do nucleófilo ao eletrófilo.'),
    err('complexo σ', 'O complexo σ continua aromático, pois mantém a carga deslocalizada no anel.', ['o carbono sp³ interrompe o ciclo de orbitais p: não aromático', 'o complexo σ não tem carga', 'a carga fica só no meta', 'não há erro'], 'Deslocalização ≠ aromaticidade.'),
    err('desprotonação', 'Na desprotonação, a base remove o H⁺ e o carbono fica com carga negativa.', ['o par da ligação C–H forma a C=C com o carbono +: restaura o anel neutro e aromático', 'a base remove o E', 'o carbono fica com carga +', 'não há erro'], 'C–H → π.'),
    err('NO₂', '–NO₂ é diretor orto/para porque tem pares isolados no O.', ['–NO₂ é retirador e diretor meta; os O não doam ao anel (N⁺ ligado ao anel)', 'o NO₂ é ativador', 'o NO₂ é diretor ipso', 'não há erro'], 'Meta diretor.'),
    err('CH₃', 'O grupo metila é diretor meta.', ['–CH₃ é ativador fraco e diretor orto/para', '–CH₃ é desativador', '–CH₃ não orienta', 'não há erro'], 'o/p.'),
    err('Cl', 'O cloro é ativador porque doa pares por ressonância.', ['o −I do Cl domina: desativador (embora orto/para diretor)', 'Cl é meta diretor', 'Cl não tem pares', 'não há erro'], 'Desativador o/p.'),
    err('Friedel–Crafts', 'Nitrobenzeno + CH₃COCl/AlCl₃ fornece m-nitroacetofenona com bom rendimento.', ['a Friedel–Crafts não funciona bem em anéis fortemente desativados', 'daria o isômero para', 'daria o isômero orto', 'não há erro'], 'Ordem invertida: acilar antes de nitrar.'),
    err('acilação', 'O íon acílio rearranja para um carbocátion mais estável, como na alquilação.', ['o acílio é estabilizado por ressonância e não rearranja', 'o acílio é um carbânion', 'o acílio é um radical', 'não há erro'], 'Sem rearranjo.'),
    err('conceitos', 'Ativação e orientação são exatamente o mesmo conceito.', ['são efeitos distintos: halogênios desativam e orientam orto/para', 'todo ativador é meta', 'todo desativador é o/p', 'não há erro'], 'Analisar separadamente.'),
    mc('Conflito', 'Bromação do 4-metilanisol ocorre principalmente:', ['orto ao OCH₃', 'orto ao CH₃', 'no carbono ipso', 'meta a ambos'], 'O mais ativador decide.', F({ 0: 'OCH3', 3: 'CH3' })),
    mc('Conflito', 'Nitração do 4-metilacetanilida:', ['orto ao NHCOCH₃', 'orto ao CH₃', 'meta ao NHCOCH₃', 'ipso'], 'NHCOCH₃ > CH₃ em ativação.', F({ 0: 'NHCOCH3', 3: 'CH3' })),
    mc('Estérico', 'No 1,3-di-terc-butilbenzeno, a posição C2 (entre os grupos):', ['é muito desfavorecida por impedimento estérico', 'é a mais reativa', 'é meta a ambos', 'é ipso'], 'Congestionada.'),
    mc('Síntese', 'Sequência para m-cloronitrobenzeno a partir do benzeno:', ['nitração → cloração', 'cloração → nitração', 'acilação → nitração', 'sulfonação → nitração'], 'NO₂ dirige meta.'),
    mc('Síntese', 'Sequência para p-nitrotolueno:', ['alquilação (CH₃Cl/AlCl₃) → nitração (separar para)', 'nitração → alquilação', 'sulfonação → alquilação', 'nitração → redução'], 'FC no nitrobenzeno falha.'),
    mc('Síntese', 'Para m-bromoanilina a partir do benzeno:', ['nitração → bromação → redução do NO₂', 'bromação → nitração → redução', 'anilina + Br₂/H₂O', 'acilação → bromação'], 'NO₂ dirige meta antes de virar NH₂.'),
    mc('Anilina + Br₂', 'Anilina + Br₂/H₂O (sem catalisador) dá:', ['2,4,6-tribromoanilina', 'm-bromoanilina', 'p-bromoanilina pura', 'não reage'], 'Anel muito ativado.'),
    mc('Proteção', 'Por que converter anilina em acetanilida antes de nitrar?', ['moderar a ativação, evitar protonação/oxidação do N e favorecer para', 'para tornar o grupo meta diretor', 'para aumentar a basicidade', 'para gerar NO₂⁺'], 'Proteção.'),
    mc('Ipso', 'Na dessulfonação, o eletrófilo que ataca o carbono ipso é:', ['H⁺', 'SO₃', 'OH⁻', 'H₂O'], 'SEA reversa.'),
    dnd('Complexo σ → orientação', 'Associe cada observação ao ataque correspondente no nitrobenzeno:', [['forma com + no C ligado ao NO₂ (ataque a C2)', 'orto'], ['forma com + no C ligado ao NO₂ (ataque a C4)', 'para'], ['nenhuma forma com + no C ligado ao NO₂', 'meta']], 'Meta evita o contribuinte desfavorável.'),
  ],
};
