/*
 * exdata.js — exercícios resolvidos (16 níveis) e propostos.
 * Contagens (elétrons, domínios, σ/π, cargas formais, hibridização) vêm
 * de struct.js a partir da mesma estrutura de Lewis desenhada.
 */
import { h, shuffle } from './widgets2d.js';
import { S, mol } from './chem2d.js';
import { L, MOLS } from './lib.js';
import { lewisSVG, centerInfo, sigmaPi, valenceElectrons, fc, nbs, fromSmiles, clone } from './struct.js';
import { orbitalImage } from './scene3d.js';
import { AO_PRESETS, cube, pair } from './orbitals.js';
import { img3d, rnd } from './ui.js';
import { boxes, config, resonate } from './m1.js';

const LF = (k, o = {}) => ({ node: () => h('div', { class: 'figs' }, h('figure', { class: 'fig' }, lewisSVG(typeof k === 'string' ? L(k) : k, Object.assign({ scale: 38, fs: 16 }, o)), o.cap ? h('figcaption', { html: o.cap }) : null)) });
const LFS = (list) => ({ node: () => h('div', { class: 'figs' }, list.map(([k, cap, o]) => h('figure', { class: 'fig' }, lewisSVG(typeof k === 'string' ? L(k) : k, Object.assign({ scale: 34, fs: 15 }, o || {})), cap ? h('figcaption', { html: cap }) : null))) });
const I3 = (k, o = {}) => ({ node: () => h('div', { class: 'figs' }, img3d(k, Object.assign({ w: 260, h: 190, lp: true }, o))) });
const ORB = (key, rot) => ({ node: () => { const P = AO_PRESETS[key]; const url = orbitalImage(P.f, cube(P.L), 30, { iso: P.iso, w: 200, h: 170, dist: P.L * 2.3, rot: rot || [0.35, 0.6, 0] }); return h('div', { class: 'figs' }, url ? h('img', { src: url, alt: 'orbital (identifique)', class: 'snap', width: 200, height: 170 }) : h('p', null, '(imagem 3D indisponível)')); } });
const BOX = (el) => ({ node: () => h('div', { class: 'figs' }, boxes(el)) });
const sv = (n) => String(n);
const ci = (k, i) => centerInfo(L(k), i);

export const SOLVED = [
  /* 1 */
  { level: 'Configuração eletrônica', title: 'Carbono', q: 'Escreva a configuração eletrônica do carbono (Z = 6). Quantos elétrons de valência ele tem? Quantos elétrons desemparelhados aparecem na configuração fundamental?', think: 'Preencha 1s, 2s e depois 2p.', hint: 'Regra de Hund: os dois elétrons 2p ficam em orbitais diferentes, com spins paralelos.', steps: ['1s² (2 e⁻) → 2s² (4 e⁻) → 2p² (6 e⁻).', 'Camada de valência n = 2: 2s² 2p² → <b>4 elétrons de valência</b>.', 'Os dois elétrons 2p ocupam dois orbitais p distintos: <b>2 desemparelhados</b>.'], solFig: BOX('C'), answer: '1s² 2s² 2p²; 4 de valência; 2 desemparelhados.' },
  { level: 'Configuração eletrônica', title: 'Oxigênio e a regra de Hund', q: 'Represente o diagrama de orbitais do oxigênio (Z = 8).', think: '8 elétrons: 1s, 2s, 2p.', hint: 'No 2p: primeiro um elétron em cada orbital, depois emparelhe.', steps: ['1s² 2s² 2p⁴.', '2p⁴: ↑↓ ↑ ↑ (um orbital emparelhado e dois com elétrons desemparelhados de spins paralelos).', 'Elétrons de valência: 6; desemparelhados: 2.'], solFig: BOX('O'), answer: '1s² 2s² 2p⁴ — 2 elétrons desemparelhados.' },
  { level: 'Configuração eletrônica', title: 'Cloro', q: 'Configuração do Cl (Z = 17) e número de elétrons de valência.', think: 'Complete n = 1 e n = 2 antes do 3s.', hint: 'Valência = camada mais externa (n = 3).', steps: ['1s² 2s² 2p⁶ 3s² 3p⁵.', 'n = 3: 3s² 3p⁵ → <b>7 elétrons de valência</b> (como o F).', 'Por isso Cl forma uma ligação e tem 3 pares isolados em CH₃Cl ou HCl.'], solFig: BOX('Cl'), answer: config(17) + '; 7 de valência.' },
  /* 2 */
  { level: 'Elétrons de valência', title: 'Nitrogênio', q: 'Quantos elétrons de valência tem o N? Como fica seu símbolo de Lewis e quantas ligações ele tende a formar quando neutro?', think: '1s² 2s² 2p³.', hint: 'Pares isolados + elétrons desemparelhados.', steps: ['Valência: 2s² 2p³ = 5 elétrons.', 'Símbolo de Lewis: um par e três elétrons isolados.', 'Três elétrons desemparelhados → <b>3 ligações</b> + 1 par isolado (como em NH₃).'], solFig: LF('NH3'), answer: '5 elétrons; 3 ligações e 1 par isolado.' },
  { level: 'Elétrons de valência', title: 'Total de elétrons do metanol', q: 'Quantos elétrons de valência há em CH₃OH?', think: 'Some os elétrons de valência de cada átomo.', hint: 'C = 4, H = 1, O = 6.', steps: ['C: 1 × 4 = 4.', 'H: 4 × 1 = 4.', 'O: 1 × 6 = 6.', 'Total = <b>14</b> elétrons = 7 pares: 5 ligações (10 e⁻) + 2 pares isolados no O (4 e⁻).'], solFig: LF('CH3OH'), answer: '14 elétrons.' },
  /* 3 */
  { level: 'Regra do octeto', title: 'Octeto do oxigênio na água', q: 'Quantos elétrons há ao redor do O em H₂O? E de cada H?', think: 'Pares ligantes contam para os dois átomos.', hint: 'O: 2 ligações + 2 pares isolados.', steps: ['O: 2 pares ligantes (4 e⁻) + 2 pares isolados (4 e⁻) = <b>8</b> → octeto.', 'H: 1 par ligante = <b>2</b> → dueto (não octeto!).'], solFig: LF('H2O'), answer: 'O: 8; H: 2.' },
  { level: 'Regra do octeto', title: 'BF₃: exceção', q: 'O boro em BF₃ obedece à regra do octeto?', think: 'B tem 3 elétrons de valência.', hint: 'Conte os elétrons ao redor do B.', steps: ['B forma 3 ligações simples com F: 3 × 2 = 6 elétrons ao redor do B.', 'B fica com <b>octeto incompleto</b> (espécie deficiente em elétrons) e um orbital p vazio.', 'Isso explica por que BF₃ aceita um par de elétrons (ácido de Lewis).'], solFig: LF('BF3'), answer: 'Não: B fica com 6 elétrons.' },
  { level: 'Regra do octeto', title: 'NO: radical', q: 'Por que é impossível que todos os átomos do NO tenham octeto?', think: 'Conte o total de elétrons.', hint: 'N (5) + O (6) = ?', steps: ['Total = 11 elétrons: número <b>ímpar</b>.', 'Com número ímpar, algum átomo fica com um elétron desemparelhado: NO é um <b>radical</b>.', 'Na estrutura de Lewis usual, o N fica com 7 elétrons.'], solFig: LF('NO'), answer: '11 elétrons (ímpar) → radical.' },
  /* 4 */
  { level: 'Ligações covalentes', title: 'Formação de H₂', q: 'Explique o mínimo na curva energia × distância H–H.', think: 'Atração entre núcleos e a densidade compartilhada × repulsão internuclear.', hint: 'O que acontece com r muito pequeno?', steps: ['Ao aproximar os átomos, os orbitais 1s se sobrepõem e a densidade eletrônica entre os núcleos atrai os dois núcleos: a energia diminui.', 'Muito perto, a repulsão núcleo–núcleo domina: a energia sobe.', 'O mínimo (r = 0,74 Å) é o <b>comprimento de ligação</b>; a profundidade (≈ 436 kJ/mol) é a energia de ligação.'], answer: 'Equilíbrio entre atração e repulsão: rₑ = 0,74 Å.' },
  { level: 'Ligações covalentes', title: 'Comprimento de C–C, C=C, C≡C', q: 'Ordene por comprimento e justifique.', think: 'Mais pares compartilhados → núcleos mais próximos.', hint: 'Etano, eteno, etino.', steps: ['C≡C (1,20 Å) < C=C (1,34 Å) < C–C (1,54 Å).', 'Mais elétrons ligantes e maior caráter s dos híbridos (sp > sp² > sp³) aproximam os núcleos.', 'A energia total cresce (≈ 347 < 614 < 839 kJ/mol), mas não proporcionalmente: a π contribui menos que a σ.'], solFig: LFS([['etano'], ['eteno'], ['etino']]), answer: 'C≡C < C=C < C–C.' },
  /* 5 */
  { level: 'Estruturas de Lewis', title: 'CO₂', q: 'Construa a estrutura de Lewis do CO₂.', think: 'C central (menos eletronegativo).', hint: '16 elétrons.', steps: ['Elétrons: 4 + 2 × 6 = 16.', 'Esqueleto O–C–O (4 e⁻); octetos dos O terminais: +12 → 16 usados.', 'C fica com apenas 4 elétrons: transforme um par isolado de cada O em ligação π.', 'Resultado: O=C=O, dois pares isolados em cada O, cargas formais zero.'], solFig: LF('CO2'), answer: 'O=C=O.' },
  { level: 'Estruturas de Lewis', title: 'HCN', q: 'Estrutura de Lewis do HCN.', think: 'C no centro; H e N terminais.', hint: '10 elétrons.', steps: ['1 + 4 + 5 = 10 elétrons.', 'H–C–N (4 e⁻); N terminal recebe 3 pares (6 e⁻): total 10, mas C tem só 4.', 'Dois pares do N viram ligações π: H–C≡N, com 1 par isolado no N.'], solFig: LF('HCN'), answer: 'H–C≡N:' },
  { level: 'Estruturas de Lewis', title: 'Formaldeído', q: 'Estrutura de Lewis do CH₂O.', think: 'C central com 2 H e 1 O.', hint: '12 elétrons.', steps: ['4 + 2 + 6 = 12.', 'Ligações simples C–H, C–H, C–O (6 e⁻); 3 pares no O (6 e⁻) → C com 6 elétrons.', 'Um par do O forma a ligação π: H₂C=O, 2 pares isolados no O.'], solFig: LF('CH2O'), answer: 'H₂C=O.' },
  { level: 'Estruturas de Lewis', title: 'Ácido acético', q: 'Estrutura de Lewis do CH₃COOH.', think: 'Grupo carboxila: C(=O)–OH.', hint: '24 elétrons.', steps: ['2 × 4 + 4 × 1 + 2 × 6 = 24.', 'Esqueleto: CH₃–C(–O)–O–H.', 'A carbonila C=O completa o octeto do C; o O da hidroxila fica com 2 pares; o O carbonílico também com 2 pares.'], solFig: LF('CH3COOH'), answer: 'CH₃–C(=O)–OH, sem cargas formais.' },
  /* 6 */
  { level: 'Carga formal', title: 'Nitrometano', q: 'Calcule as cargas formais do N e dos O no CH₃NO₂ (estrutura abaixo).', fig: LF('nitrometano', { fc: false }), think: 'CF = V − não ligantes − ½ ligantes.', hint: 'N tem 4 ligações e nenhum par.', steps: ['N: 5 − 0 − ½(8) = <b>+1</b>.', 'O da dupla: 6 − 4 − ½(4) = <b>0</b>.', 'O da simples: 6 − 6 − ½(2) = <b>−1</b>.', 'Soma = 0 (molécula neutra).'], solFig: LF('nitrometano'), answer: 'N +1; O(=) 0; O(–) −1.' },
  { level: 'Carga formal', title: 'Íon amônio', q: 'Onde está a carga no NH₄⁺?', think: 'Calcule a CF do N.', hint: 'N com 4 ligações e nenhum par.', steps: ['N: 5 − 0 − ½(8) = +1.', 'H: 1 − 0 − ½(2) = 0.', 'A carga +1 é formalmente do N.'], solFig: LF('NH4'), answer: 'N +1.' },
  { level: 'Carga formal', title: 'Monóxido de carbono', q: 'Qual é a melhor estrutura de Lewis do CO e quais as cargas formais?', think: 'Compare :C≡O: com C=O.', hint: 'Octetos completos pesam muito.', steps: ['10 elétrons. Em C=O, o C ficaria com 6 elétrons.', 'Com ligação tripla :C≡O:, ambos têm octeto.', 'CF: C = 4 − 2 − 3 = −1; O = 6 − 2 − 3 = +1.', 'Embora a carga negativa fique no C (menos eletronegativo), os octetos completos tornam essa a estrutura mais plausível — os critérios são tendências, não regras absolutas.'], solFig: LF('CO'), answer: '⁻:C≡O:⁺' },
  /* 7 */
  { level: 'Ressonância', title: 'Acetato', q: 'Desenhe as formas de ressonância do acetato e descreva o híbrido.', think: 'Um O tem 3 pares e carga −1; o outro faz C=O.', hint: 'Mova um par isolado para formar π e a π para o outro O.', steps: ['Seta 1: par isolado do O⁻ → ligação C–O (forma π).', 'Seta 2: par π da C=O → O (vira par isolado).', 'Forma B: a dupla e a carga trocaram de oxigênio; os átomos não se moveram.', 'Híbrido: duas ligações C–O <b>iguais</b> (≈ 1,26 Å, ordem 1½) e carga −½ em cada O.'], solFig: LFS([['acetato', 'A'], [resonate(L('acetato'), 'acetato'), 'B']]), answer: 'Duas formas equivalentes; híbrido com C–O iguais.' },
  { level: 'Ressonância', title: 'Cátion alila', q: 'Mostre a ressonância do cátion alila.', think: 'A ligação π vizinha ao C⁺ pode se deslocar.', hint: 'Par π → ligação C–C+.', steps: ['Par π da C=C desloca-se para formar π com o C⁺.', 'A carga + passa para o outro carbono terminal.', 'Híbrido: carga +½ nos dois carbonos terminais, ligações C–C equivalentes.'], solFig: LFS([['alilaC', 'A'], [resonate(L('alilaC'), 'alilaC'), 'B']]), answer: 'Duas formas equivalentes; carga + deslocalizada nos C terminais.' },
  { level: 'Ressonância', title: 'Carbonato', q: 'Quantas formas de ressonância equivalentes tem o CO₃²⁻? Qual a ordem de cada C–O?', think: 'A ligação dupla pode estar em qualquer um dos três O.', hint: '3 formas.', steps: ['Três formas equivalentes, com a C=O em cada um dos O.', 'Cada ligação C–O é dupla em 1 de 3 formas: ordem média = 1⅓.', 'Carga −2 distribuída: −⅔ em cada O. As três C–O são idênticas no íon real.'], solFig: LF('carbonato'), answer: '3 formas; ordem 1⅓.' },
  /* 8 */
  { level: 'VSEPR', title: 'Domínios em CO₂ e H₂O', q: 'Quantos domínios há ao redor do átomo central de CO₂ e de H₂O?', think: 'Ligação dupla conta como 1 domínio.', hint: 'Pares isolados também são domínios.', steps: ['CO₂: duas ligações duplas = <b>2 domínios</b> (AX₂) → linear, 180°.', 'H₂O: 2 ligações + 2 pares = <b>4 domínios</b> (AX₂E₂) → eletrônica tetraédrica, molecular angular.'], solFig: LFS([['CO2'], ['H2O']]), answer: 'CO₂: 2; H₂O: 4.' },
  { level: 'VSEPR', title: 'SO₂', q: 'Preveja a geometria do SO₂.', think: 'S com 2 ligações duplas e 1 par isolado.', hint: 'AX₂E.', steps: ['3 domínios ao redor do S: eletrônica trigonal planar.', 'Molecular: <b>angular</b> (AX₂E), ângulo um pouco menor que 120° (≈ 119°).', 'Compare com CO₂: lá não há par isolado no átomo central → linear.'], solFig: LF('SO2'), answer: 'Angular, ≈ 119°.' },
  /* 9 */
  { level: 'Geometria molecular', title: 'NH₃: eletrônica × molecular', q: 'Diferencie geometria eletrônica e molecular para NH₃.', think: '4 domínios, 1 é par isolado.', hint: 'A geometria molecular considera só os átomos.', steps: ['Eletrônica (todos os domínios): tetraédrica.', 'Molecular (posições dos átomos): <b>piramidal trigonal</b>.', 'O par isolado ocupa mais espaço e comprime H–N–H para ≈ 107°.'], solFig: I3('NH3'), answer: 'Tetraédrica × piramidal trigonal.' },
  { level: 'Geometria molecular', title: 'H₃O⁺', q: 'Qual é a geometria do íon hidrônio?', think: 'O com 3 ligações e 1 par.', hint: 'Isoeletrônico com NH₃.', steps: ['AX₃E: eletrônica tetraédrica.', 'Molecular: piramidal trigonal (como NH₃).', 'Carga formal +1 no O.'], solFig: LF('H3O'), answer: 'Piramidal trigonal.' },
  /* 10 */
  { level: 'Orbitais atômicos', title: 'Nós em 2s e 2p', q: 'Compare os nós de 2s e 2p.', think: 'Nó radial (esfera) × plano nodal.', hint: 'Número total de nós = n − 1.', steps: ['n = 2 → 1 nó em cada.', '2s: <b>nó radial</b> (esfera onde ψ = 0, em r = 2a₀ no hidrogênio).', '2p: <b>plano nodal</b> passando pelo núcleo (ex.: plano xy para 2p_z).'], solFig: ORB('2pz'), answer: '2s: nó esférico; 2p: plano nodal.' },
  { level: 'Orbitais atômicos', title: 'O que significam as cores de um orbital p?', q: 'Os dois lóbulos de um 2p são desenhados em cores diferentes. Isso indica cargas + e −?', think: 'Pense em ψ, não em carga.', hint: 'A densidade |ψ|² é igual nos dois lóbulos.', steps: ['As cores indicam o <b>sinal (fase)</b> da função de onda ψ.', '|ψ|² é igual nos dois lóbulos: o elétron tem a mesma probabilidade de estar em qualquer um deles.', 'A fase importa para a combinação de orbitais: fases iguais somam (ligante), opostas se cancelam (nó, antiligante).'], answer: 'Não: são fases de ψ, não cargas.' },
  /* 11 */
  { level: 'Orbitais moleculares', title: 'Diagrama de H₂', q: 'Monte o diagrama de OM do H₂ e calcule a ordem de ligação.', think: '1s + 1s → σ e σ*.', hint: 'Dois elétrons, preencha o mais baixo.', steps: ['Combinação em fase → σ1s (abaixo dos 1s); fora de fase → σ*1s (acima).', 'Os 2 elétrons ocupam σ1s com spins opostos.', 'Ordem = ½(2 − 0) = <b>1</b>: ligação simples.'], answer: 'Ordem 1.' },
  { level: 'Orbitais moleculares', title: 'He₂ existe?', q: 'Use a ordem de ligação para prever se He₂ é estável.', think: '4 elétrons.', hint: '2 em σ, 2 em σ*.', steps: ['σ1s² σ*1s².', 'Ordem = ½(2 − 2) = 0.', 'Sem ligação líquida: He₂ não forma molécula estável.'], answer: 'Ordem 0 — não.' },
  /* 12 */
  { level: 'Ligações σ e π', title: 'Propeno', q: 'Quantas ligações σ e π há no propeno (CH₃CH=CH₂)?', think: 'Cada ligação tem uma σ.', hint: 'Conte todas as ligações, incluindo C–H.', steps: ['Ligações: 6 C–H + 2 C–C = 8 ligações → <b>8 σ</b>.', 'A dupla acrescenta <b>1 π</b>.', 'Total de pares ligantes: 9.'], solFig: LF('propeno'), answer: `${sigmaPi(L('propeno')).s} σ e ${sigmaPi(L('propeno')).p} π.` },
  { level: 'Ligações σ e π', title: 'HCN: orbitais', q: 'Quais orbitais formam as ligações do HCN?', think: 'C e N são sp.', hint: 'Dois p de cada átomo sobram.', steps: ['H–C: σ(1s–sp).', 'C–N: σ(sp–sp) + 2 π(p–p), em planos perpendiculares.', 'N: o par isolado ocupa o outro híbrido sp.', 'Total: 2 σ e 2 π.'], solFig: LF('HCN'), answer: '2 σ, 2 π.' },
  { level: 'Ligações σ e π', title: 'CO₂', q: 'σ e π no CO₂; os dois π estão no mesmo plano?', think: 'C é sp.', hint: 'C tem dois p perpendiculares.', steps: ['2 σ (C–O) e 2 π.', 'O C (sp) usa p_y para π com um O e p_z para π com o outro: os dois sistemas π são <b>perpendiculares</b>.'], answer: '2 σ, 2 π perpendiculares.' },
  /* 13 */
  { level: 'Hibridização sp³', title: 'Metano', q: 'Descreva o C do metano: domínios, hibridização, geometria e orbitais das ligações.', think: '4 ligações, nenhum par.', hint: 'sp³.', steps: ['4 domínios → sp³ → tetraédrico, 109,5°.', 'Cada C–H é σ(sp³–1s).', 'Os quatro híbridos são equivalentes: as 4 ligações C–H são iguais (o que a configuração 2s² 2p² sozinha não explicaria).'], solFig: I3('CH4'), answer: 'sp³, tetraédrico, σ(sp³–1s).' },
  { level: 'Hibridização sp³', title: 'Etano e rotação', q: 'Por que há rotação relativamente livre em torno de C–C no etano?', think: 'Simetria da ligação σ.', hint: 'A sobreposição frontal não muda com a rotação.', steps: ['C–C é σ(sp³–sp³), com simetria cilíndrica em torno do eixo.', 'Girar um CH₃ não altera a sobreposição σ: não se rompe ligação.', 'Há apenas uma pequena barreira (≈ 12 kJ/mol) entre conformações alternada e eclipsada.'], solFig: I3('etano'), answer: 'A sobreposição σ é preservada na rotação.' },
  /* 14 */
  { level: 'Hibridização sp²', title: 'Eteno', q: 'Descreva os carbonos do eteno.', think: '3 domínios cada.', hint: 'sp² + p.', steps: ['Cada C: 3 domínios → sp², trigonal planar, 120°.', 'C–C: σ(sp²–sp²) + π(p–p lateral).', 'C–H: σ(sp²–1s).', 'Os 6 átomos ficam no mesmo plano (os p precisam estar paralelos).'], solFig: I3('eteno'), answer: 'sp², planar, C=C = σ + π.' },
  { level: 'Hibridização sp²', title: 'Carbonila do formaldeído', q: 'Hibridização do C e do O no CH₂O; que orbitais formam a C=O?', think: 'C: 3 domínios; O: 1 ligado + 2 pares.', hint: 'No modelo usual, ambos sp².', steps: ['C: 3 domínios → sp² (trigonal planar).', 'O: 3 domínios (1 ligado + 2 pares) → descrito como sp².', 'C=O: σ(sp²–sp²) + π(p–p). O O é mais eletronegativo: ligação polarizada, C δ+ (importante para a reatividade futura).'], solFig: LF('CH2O'), answer: 'C e O sp²; C=O = σ + π.' },
  /* 15 */
  { level: 'Hibridização sp', title: 'Etino', q: 'Descreva os carbonos do etino.', think: '2 domínios cada.', hint: 'sp + 2 p.', steps: ['2 domínios → sp → linear, 180°.', 'C≡C: σ(sp–sp) + 2 π (p_y–p_y e p_z–p_z, perpendiculares).', 'C–H: σ(sp–1s); ângulo H–C–C = 180°.'], solFig: I3('etino'), answer: 'sp, linear, σ + 2π.' },
  { level: 'Hibridização sp', title: 'Acetonitrila', q: 'Hibridização de cada carbono em CH₃–C≡N.', think: 'Conte domínios em cada C.', hint: 'CH₃: 4; C da nitrila: 2.', steps: ['CH₃: 4 domínios → sp³.', 'C≡N: 2 domínios → sp; N também sp (1 ligado + 1 par).', 'C–C≡N é linear.'], solFig: LF('acetonitrila'), answer: 'sp³ e sp.' },
  /* 16 */
  { level: 'Problemas integrados', title: 'Eteno completo', q: 'Para o eteno: Lewis, cargas formais, geometria de cada C, hibridização, σ, π, orbitais, ângulos e rotação restrita.', think: 'Integre tudo.', hint: 'C₂H₄: 12 elétrons.', steps: ['Lewis: H₂C=CH₂ (12 e⁻), cargas formais nulas.', 'Cada C: 3 domínios → trigonal planar, sp².', '5 σ (4 C–H + 1 C–C) e 1 π.', 'σ(sp²–1s), σ(sp²–sp²), π(p–p).', 'Ângulos ≈ 120°; molécula plana.', 'Girar C=C desalinha os p e destrói a π: rotação restrita (isomeria E/Z).'], solFig: I3('eteno'), answer: 'sp², plano, 5 σ + 1 π, rotação restrita.' },
  { level: 'Problemas integrados', title: 'Etino completo', q: 'Para o etino: Lewis, hibridização, geometria, σ/π, orbitais p e ângulo H–C–C.', think: 'C₂H₂: 10 elétrons.', hint: 'Ligação tripla.', steps: ['Lewis: H–C≡C–H.', 'Cada C: sp, linear.', '3 σ e 2 π.', 'Dois pares de orbitais p perpendiculares formam as duas π.', 'H–C–C = 180°.'], solFig: I3('etino'), answer: 'sp, linear, 3 σ + 2 π, 180°.' },
  { level: 'Problemas integrados', title: 'Carbonila (CH₂O) completa', q: 'Lewis, pares isolados, geometria e hibridização do C, σ e π da carbonila, polarização.', think: 'Formaldeído.', hint: '12 elétrons.', steps: ['H₂C=O; O com 2 pares isolados.', 'C: trigonal planar, sp², ≈ 120°.', 'C=O: 1 σ + 1 π; total 3 σ e 1 π.', 'O mais eletronegativo: C δ+ / O δ− — o C carbonílico será eletrófilo nas reações.'], solFig: LF('CH2O'), answer: 'sp² planar; 3 σ, 1 π; C δ+.' },
  { level: 'Problemas integrados', title: 'CH₃CH=CHC≡N', q: 'Analise CH₃–CH=CH–C≡N: hibridização e geometria de cada centro, σ, π, orbitais p, regiões planas e lineares.', think: 'Átomo por átomo.', hint: 'Domínios: 4, 3, 3, 2, 2.', steps: ['C1 (CH₃): sp³, tetraédrico.', 'C2 e C3: sp², trigonais planos — a região C1–C2=C3–C4 é plana.', 'C4 e N: sp, lineares — C3–C4≡N alinhados.', `${sigmaPi(L('final')).s} σ e ${sigmaPi(L('final')).p} π: 1 π (C=C) + 2 π (C≡N).`, 'Orbitais p em ligações π: 2 (C=C) + 4 (C≡N) = 6.'], solFig: I3('final', { dist: 9 }), answer: 'sp³, sp², sp², sp, sp; 9 σ, 3 π.' },
  { level: 'Problemas integrados', title: 'Amida: o modelo e a ressonância', q: 'Pela contagem de domínios, o N da acetamida seria sp³. Por que ele é praticamente plano?', think: 'O par isolado do N está ao lado de C=O.', hint: 'Ressonância N–C=O ↔ N⁺=C–O⁻.', steps: ['N: 3 ligados + 1 par = 4 domínios → contagem sugere sp³ (piramidal).', 'O par isolado participa de ressonância com a C=O (forma N⁺=C–O⁻): precisa estar num orbital p paralelo ao π.', 'Assim o N é melhor descrito como sp² e a amida é plana. Hibridização é um <b>modelo</b>: a deslocalização prevalece.'], solFig: LF('acetamida'), answer: 'Ressonância → N ≈ sp² (plano).' },
];

/* ===================================================================
 * Propostos
 * =================================================================== */
const mc = (title, q, o, e, extra = {}) => Object.assign({ title, type: 'mc', q, o, a: 0, e }, extra);
const tf = (title, items, e) => ({ title, type: 'tf', q: 'Marque V ou F:', items, e });
const dnd = (title, q, pairs, e) => ({ title, type: 'dnd', q, pairs, e });
const valQ = (el, n) => mc('Elétrons de valência', `Quantos elétrons de valência tem o <b>${el}</b>?`, [sv(n), sv(n + 1), sv(n - 1), sv(8 - n || 2)].filter((x, i, a) => a.indexOf(x) === i && +x > 0), `${el}: ${n} elétrons na camada de valência.`);
const domQ = (k, i) => { const c = ci(k, i); return mc('Domínios', `Quantos domínios eletrônicos há ao redor do <b>${L(k).atoms[i].el}</b> destacado?`, [c.D, ...[2, 3, 4, 5].filter((x) => x !== c.D)].slice(0, 4).map(sv), `${c.X} ligados + ${c.E} pares = ${c.D} (${c.axe}).`, { fig: LF(k, { halo: { [i]: 'g' } }) }); };
const geoQ = (k, i) => { const c = ci(k, i); const opts = [c.mgeo, ...['linear', 'trigonal planar', 'tetraédrica', 'angular', 'piramidal trigonal'].filter((x) => x !== c.mgeo)].slice(0, 4); return mc('Geometria', `Qual é a geometria molecular em torno do <b>${L(k).atoms[i].el}</b> em ${MOLS[k][1]}?`, opts, `${c.axe}: eletrônica ${c.egeo}, molecular ${c.mgeo}, ≈ ${c.ang}.`, { fig: LF(k, { halo: { [i]: 'g' } }) }); };
const hybQ = (k, i) => { const c = ci(k, i); return mc('Hibridização', `Hibridização do <b>${L(k).atoms[i].el}</b> destacado em ${MOLS[k][1]}?`, [c.hyb, ...['sp³', 'sp²', 'sp'].filter((x) => x !== c.hyb)], `${c.D} domínios → ${c.hyb}.`, { fig: LF(k, { halo: { [i]: 'g' } }) }); };
const spQ = (k) => { const s = sigmaPi(L(k)); return mc('σ e π', `Quantas ligações σ e π há em <b>${MOLS[k][1]}</b>?`, [`${s.s} σ e ${s.p} π`, `${s.s + s.p} σ e ${s.p} π`, `${s.s} σ e ${s.p + 1} π`, `${s.s - 1} σ e ${s.p} π`], 'Cada ligação tem 1 σ; dupla: +1 π; tripla: +2 π.', { fig: LF(k) }); };
const fcQ = (k, i) => { const f = fc(L(k), i); const fs = (x) => (x > 0 ? '+' + x : String(x)); return mc('Carga formal', `Carga formal do <b>${L(k).atoms[i].el}</b> destacado?`, [fs(f), ...[-1, 0, 1, 2].filter((x) => x !== f).map(fs)].slice(0, 4), `CF = V − não ligantes − ½ ligantes = ${fs(f)}.`, { fig: LF(k, { halo: { [i]: 'g' }, fc: false }) }); };
const eQ = (k) => { const n = valenceElectrons(L(k)); return mc('Contagem de elétrons', `Quantos elétrons de valência há em <b>${MOLS[k][1]}</b>?`, [n, n + 2, n - 2, n + 1].map(sv), `Some os elétrons de valência e ajuste pela carga: ${n}.`); };
const orbQ = (key, ans, opts, e) => mc('Identifique o orbital', 'Que orbital está representado (cores = fases)?', [ans, ...opts], e, { fig: ORB(key) });
const img3Q = (k, i, what) => { const c = ci(k, i); return what === 'geo' ? mc('Modelo 3D', 'Qual é a geometria em torno do átomo central deste modelo?', [c.mgeo, ...['linear', 'trigonal planar', 'tetraédrica', 'angular', 'piramidal trigonal'].filter((x) => x !== c.mgeo)].slice(0, 4), `${MOLS[k][1]}: ${c.axe}.`, { fig: I3(k) }) : mc('Modelo 3D', 'Qual é a hibridização do átomo central deste modelo?', [c.hyb, ...['sp³', 'sp²', 'sp'].filter((x) => x !== c.hyb)], `${MOLS[k][1]}: ${c.D} domínios → ${c.hyb}.`, { fig: I3(k) }); };
const bad = (s) => { const LS = fromSmiles(s); return LS; };

export const PROPOSED = {
  easy: [
    valQ('C', 4), valQ('N', 5), valQ('O', 6), valQ('F', 7), valQ('H', 1),
    mc('Configuração', 'Configuração eletrônica do nitrogênio (Z = 7):', ['1s² 2s² 2p³', '1s² 2s³ 2p²', '1s² 2p⁵', '1s² 2s² 2p⁵'], '2 + 2 + 3 = 7.'),
    mc('Configuração', 'Quantos elétrons desemparelhados tem o C no estado fundamental?', ['2', '4', '0', '1'], '2p²: dois elétrons em orbitais p diferentes (Hund).'),
    mc('Configuração', 'O princípio de exclusão de Pauli diz que:', ['dois elétrons no mesmo orbital têm spins opostos', 'os elétrons ocupam primeiro os orbitais de maior energia', 'elétrons emparelham antes de ocupar orbitais vazios', 'um orbital comporta até 4 elétrons'], 'Máximo de 2 por orbital, com spins opostos.'),
    domQ('CH4', 0), domQ('CO2', 1), domQ('H2O', 0), domQ('CH2O', 0),
    geoQ('CH4', 0), geoQ('BF3', 1), geoQ('CO2', 1), geoQ('NH3', 0),
    spQ('etano'), spQ('eteno'), spQ('etino'), spQ('CO2'),
    tf('Octeto e ligações', [['O H segue a regra do dueto.', 'V'], ['BF₃ tem octeto completo no B.', 'F'], ['Uma ligação dupla tem 4 elétrons compartilhados.', 'V']], 'H: 2 elétrons; B em BF₃: 6.'),
    tf('Orbitais', [['Orbitais são trajetórias dos elétrons.', 'F'], ['|ψ|² está ligado à densidade de probabilidade.', 'V'], ['Um orbital 2p tem um plano nodal.', 'V']], 'Orbitais não são trajetórias.'),
    tf('VSEPR', [['Uma ligação dupla conta como um domínio.', 'V'], ['Par isolado não conta como domínio.', 'F'], ['CH₄ é tetraédrico.', 'V']], 'Ligação múltipla = 1 domínio; par isolado = 1 domínio.'),
    dnd('Elemento → configuração', 'Arraste cada configuração até o elemento:', [['H', '1s¹'], ['C', '1s² 2s² 2p²'], ['O', '1s² 2s² 2p⁴'], ['F', '1s² 2s² 2p⁵'], ['Cl', '1s² 2s² 2p⁶ 3s² 3p⁵']], 'Configurações no estado fundamental.'),
    dnd('Molécula → geometria', 'Arraste a geometria até a molécula:', [['CH₄', 'tetraédrica'], ['NH₃', 'piramidal trigonal'], ['H₂O', 'angular'], ['CO₂', 'linear'], ['BF₃', 'trigonal planar']], 'VSEPR: domínios e pares isolados.'),
  ],
  mid: [
    fcQ('nitrometano', 1), fcQ('nitrometano', 3), fcQ('NH4', 0), fcQ('acetato', 3), fcQ('CO', 0),
    eQ('acetato'), eQ('CH3COOH'), eQ('carbonato'),
    mc('Ressonância', 'Qual é uma forma de ressonância válida do acetato (forma A abaixo)?', [{ svg: () => lewisSVG(resonate(L('acetato'), 'acetato'), { scale: 30, fs: 14 }) }, { svg: () => lewisSVG(bad('C=C([O-])O'), { scale: 30, fs: 14 }) }, { svg: () => lewisSVG(bad('CC(O)=O'), { scale: 30, fs: 14 }) }], 'Só os elétrons se movem. A 2ª muda a posição de um H (é outra substância); a 3ª é o ácido acético (tem um H a mais).', { struct: true, fig: LF('acetato') }),
    mc('Ressonância', 'O que muda entre duas formas de ressonância?', ['apenas a posição de elétrons π e pares isolados', 'a posição dos átomos', 'as ligações σ', 'o número total de elétrons'], 'Conectividade σ e átomos fixos.'),
    mc('Ressonância', 'O híbrido de ressonância do acetato tem:', ['duas ligações C–O iguais e −½ em cada O', 'uma C=O e uma C–O alternando rapidamente', 'carga −1 sempre no mesmo O', 'duas ligações duplas'], 'Formas canônicas não se interconvertem: a molécula real é o híbrido.'),
    geoQ('H2O', 0), geoQ('SO2', 1), geoQ('H3O', 0), geoQ('imina', 1),
    hybQ('CH3OH', 1), hybQ('HCN', 0), hybQ('acetona', 1), hybQ('propeno', 0), hybQ('acetonitrila', 1),
    orbQ('1s', '1s', ['2p', 'sp³', '2s'], 'Esfera sem nós (em 1s).'), orbQ('2pz', '2p', ['sp³', '1s', 'sp'], 'Dois lóbulos iguais de fases opostas.'), orbQ('sp3', 'híbrido (sp³)', ['2p', '2s', '1s'], 'Um lóbulo grande e um pequeno de fase oposta.'), orbQ('2s', '2s (em corte: esfera interna e casca externa)', ['1s', '2p', 'sp²'], '2s tem um nó radial.'),
    dnd('Geometria → hibridização', 'Associe:', [['tetraédrica (4 domínios)', 'sp³'], ['trigonal planar (3 domínios)', 'sp²'], ['linear (2 domínios)', 'sp']], 'Domínios ↔ híbridos.'),
    dnd('Ligação → σ/π', 'Associe a ligação à sua composição:', [['C–C', '1 σ'], ['C=C', '1 σ + 1 π'], ['C≡C', '1 σ + 2 π']], 'Toda ligação tem uma σ.'),
    dnd('Orbital → descrição', 'Associe:', [['1s', 'esférico, sem nós'], ['2s', 'esférico, 1 nó radial'], ['2p', 'dois lóbulos, plano nodal'], ['sp³', 'lóbulo grande + lóbulo pequeno']], 'Formas qualitativas.'),
    tf('OM', [['Combinação fora de fase gera um nó entre os núcleos.', 'V'], ['Elétrons em σ* aumentam a ordem de ligação.', 'F'], ['A ordem de ligação do H₂ é 1.', 'V']], 'Ordem = ½(ligantes − antiligantes).'),
    tf('σ e π', [['π tem densidade ao longo do eixo internuclear.', 'F'], ['π resulta de sobreposição lateral de p paralelos.', 'V'], ['Uma ligação tripla tem 2 σ e 1 π.', 'F']], 'π: nó no eixo; tripla: 1 σ + 2 π.'),
    tf('Hibridização', [['Hibridização é um modelo matemático de descrição orbital.', 'V'], ['Carbono sp tem 2 orbitais p não hibridizados.', 'V'], ['Carbono sp³ é plano.', 'F']], 'sp³ é tetraédrico.'),
  ],
  hard: [
    mc('Detecte o erro', 'Qual é o erro desta estrutura?', ['carbono com cinco ligações', 'H com duas ligações', 'falta de pares no O', 'nenhum'], 'O carbono faz no máximo 4 ligações (octeto).', { fig: { node: () => { const sp = new S(); const c = sp.a(0, 0, 'C'); [90, 162, 234, 306, 18].forEach((d, k) => sp.br(c, d, k === 4 ? 'CH₃' : 'H')); return h('div', { class: 'figs' }, mol(sp, { scale: 44, fs: 18 })); } } }),
    mc('Detecte o erro', 'Em “H–O–H–H” (um H ligado a dois átomos), qual é o erro?', ['H com duas ligações covalentes comuns', 'O sem pares isolados', 'carbono pentavalente', 'nenhum'], 'H faz uma ligação (dueto).'),
    mc('Detecte o erro', 'Um aluno desenhou CO₂ com 18 elétrons. Qual o problema?', ['número total de elétrons incorreto (deveria ser 16)', 'geometria errada', 'C deveria ter carga', 'falta H'], '4 + 2 × 6 = 16.'),
    mc('Detecte o erro', 'Uma “forma de ressonância” foi obtida movendo um H de um O para outro. O erro é:', ['ressonância não move átomos', 'faltam setas', 'carga errada', 'nenhum'], 'Mover átomos gera outra substância (tautômero), não ressonância.'),
    mc('Detecte o erro', 'Para o CO₂, alguém contou 4 domínios ao redor do C (cada dupla = 2). Erro?', ['ligação dupla conta como um domínio', 'pares isolados do O contam para o C', 'nenhum: são 4', 'o C tem pares isolados'], '2 domínios → linear.'),
    mc('Detecte o erro', 'Um modelo mostra o C do metano com os quatro H no mesmo plano (90°). Erro?', ['C sp³ é tetraédrico (109,5°), não plano', 'C deveria ser sp', 'H deveria ter pares', 'nenhum'], 'Quatro domínios → tetraedro.'),
    mc('Detecte o erro', 'Um desenho mostra o etino com H–C–C de 109,5°. Erro?', ['C sp é linear (180°)', 'etino tem C sp³', 'etino tem 4 π', 'nenhum'], '2 domínios → 180°.'),
    mc('Detecte o erro', '“A dupla C=C é formada por duas ligações σ.” Erro?', ['a dupla tem 1 σ + 1 π', 'a dupla tem 2 π', 'a dupla tem 1 σ apenas', 'nenhum'], 'Uma ligação dupla nunca são duas σ.'),
    mc('Detecte o erro', 'Um desenho de “ligação π” mostra orbitais p perpendiculares entre si. Erro?', ['π exige orbitais p paralelos', 'π é frontal', 'faltam elétrons', 'nenhum'], 'Sem sobreposição lateral não há π.'),
    mc('Detecte o erro', '“O lóbulo azul do orbital p é a região positiva (com falta de elétrons).” Erro?', ['as cores são fases de ψ, não cargas', 'o lóbulo azul é negativo', 'orbitais p não têm lóbulos', 'nenhum'], 'Fase ≠ carga.'),
    img3Q('NH3', 0, 'geo'), img3Q('BF3', 1, 'geo'), img3Q('etino', 0, 'hyb'), img3Q('CH2O', 0, 'hyb'), img3Q('H2O', 0, 'geo'),
    mc('Integrado', 'No metanol, o O é descrito como:', ['sp³, angular (C–O–H ≈ 108°), 2 pares isolados', 'sp², plano', 'sp, linear', 'sem pares isolados'], '2 ligações + 2 pares = 4 domínios.', { fig: LF('CH3OH') }),
    mc('Integrado', 'Em CH₃CH=CHC≡N, quantos carbonos são sp²?', ['2', '1', '3', '4'], 'Os dois carbonos da C=C.', { fig: LF('final') }),
    mc('Integrado', 'Em CH₃CH=CHC≡N, quantas ligações π?', ['3', '2', '4', '1'], 'C=C: 1; C≡N: 2.', { fig: LF('final') }),
    mc('Integrado', 'Qual afirmação sobre o formaldeído é correta?', ['C sp², plano, C=O com 1 σ e 1 π, C δ+', 'C sp³, tetraédrico', 'C sp, linear', 'O sem pares isolados'], 'Carbonila: sp², polarizada.'),
    mc('Integrado', 'Por que a rotação em torno de C=C é restrita?', ['girar destrói a sobreposição lateral dos p (π)', 'a σ C–C se rompe ao girar', 'os H se repelem muito', 'os C são sp³'], 'A π depende de p paralelos.'),
    mc('Integrado', 'O N da formamida (HCONH₂) é praticamente plano porque:', ['seu par isolado participa de ressonância com C=O', 'N é sempre sp²', 'não tem par isolado', 'é sp'], 'Deslocalização → N ≈ sp².'),
    dnd('Estrutura → forma de ressonância', 'Associe cada espécie à sua forma de ressonância (descrição):', [['acetato', 'C=O no outro oxigênio, −1 no primeiro'], ['cátion alila', '+ no outro carbono terminal'], ['carbonato', 'C=O em qualquer dos três O']], 'Elétrons se movem; átomos não.'),
    { title: 'Comprimentos', type: 'order', q: 'Ordene do menor para o maior comprimento de ligação:', items: [['t', 'C≡C'], ['d', 'C=C'], ['s', 'C–C']].map(([id, label]) => ({ id, label })), correct: ['t', 'd', 's'], top: 'mais curta', bottom: 'mais longa', explain: '1,20 < 1,34 < 1,54 Å.', e: '1,20 < 1,34 < 1,54 Å.' },
    { title: 'Ângulos', type: 'order', q: 'Ordene do maior para o menor ângulo H–X–H:', items: [['c', 'CH₄'], ['n', 'NH₃'], ['o', 'H₂O']].map(([id, label]) => ({ id, label })), correct: ['c', 'n', 'o'], top: 'maior', bottom: 'menor', explain: '109,5° > 107° > 104,5°: cada par isolado comprime mais os ângulos.', e: 'Pares isolados ocupam mais espaço.' },
    mc('OM', 'He₂⁺ (3 elétrons) tem ordem de ligação:', ['½', '0', '1', '1½'], '½(2 − 1) = ½.'),
  ],
};
void shuffle; void rnd; void clone; void nbs; void pair; void config;
