/*
 * exdata.js — exercícios resolvidos (13 níveis) e propostos (20 fáceis,
 * 20 intermediários, 20 avançados). Figuras de anéis vêm do mesmo modelo
 * (arom.js) usado na análise.
 */
import { h } from './widgets2d.js';
import { S } from './chem2d.js';
import { MOLS, mono } from './arom.js';
import { benz, svgS } from './arom2d.js';
import { ringFig } from './ui.js';

const RF = (...list) => ({ node: () => h('div', { class: 'figs' }, list.map((x) => (Array.isArray(x) ? ringFig(x[0], Object.assign({ scale: 34, fs: 15 }, x[1] || {})) : ringFig(x, { scale: 34, fs: 15 })))) });
const AR = (form, E = 'E') => ({ node: () => { const s = new S(); benz(s, { arenium: form, E }); return h('div', { class: 'figs' }, svgS(s, { scale: 38 })); } });
const BZ = (o) => ({ node: () => { const s = new S(); benz(s, o); return h('div', { class: 'figs' }, svgS(s, { scale: 38 })); } });
const D = {
  cicloexadieno14: mono(['CH2', 'C', 'C', 'CH2', 'C', 'C'], [[1, 2], [4, 5]], { name: 'ciclo-hexa-1,4-dieno', f: 'C₆H₈' }),
  oxazol: mono(['O', 'C', 'N', 'C', 'C'], [[1, 2], [3, 4]], { name: 'oxazol', f: 'C₃H₃NO' }),
  ciclononatetraenila: mono(['C-', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C'], [[1, 2], [3, 4], [5, 6], [7, 8]], { name: 'ânion ciclononatetraenila', f: 'C₉H₉⁻' }),
};

export const SOLVED = [
  /* 1. Estrutura do benzeno */
  { level: 'Estrutura do benzeno', title: 'Hibridização e geometria', q: 'Qual a hibridização dos carbonos do benzeno, a geometria em torno de cada um e os ângulos C–C–C?', think: 'Cada carbono forma três ligações σ (2 C + 1 H).', hint: 'Três domínios → sp².', steps: ['Cada C liga-se a dois C e a um H: três domínios → <b>sp²</b>.', 'Geometria trigonal planar, ângulos de <b>120°</b> — coincide com o ângulo interno do hexágono regular.', 'Sobra um orbital <b>p</b> não hibridizado em cada C, perpendicular ao plano do anel.'], solFig: RF('benzeno'), answer: 'sp², trigonal planar, 120°; um orbital p por carbono.' },
  { level: 'Estrutura do benzeno', title: 'Comprimentos de ligação', q: 'As ligações C–C do benzeno medem todas ≈ 1,39 Å. Por que isso é incompatível com uma estrutura de três duplas fixas?', think: 'Compare com C–C (1,54 Å) e C=C (1,34 Å).', hint: 'Duplas fixas → dois comprimentos diferentes.', steps: ['Se houvesse duplas fixas, teríamos três ligações curtas (≈ 1,34 Å) e três longas (≈ 1,54 Å).', 'Observa-se um único valor, intermediário (1,39 Å).', 'Os elétrons π estão <b>deslocalizados</b> igualmente pelas seis ligações: ordem de ligação ≈ 1,5.'], answer: 'Um único comprimento intermediário indica deslocalização, não duplas alternadas.' },
  { level: 'Estrutura do benzeno', title: 'Planaridade', q: 'Por que o anel do benzeno precisa ser plano?', think: 'O que acontece com orbitais p que deixam de ser paralelos?', hint: 'Sobreposição lateral.', steps: ['A deslocalização exige sobreposição lateral entre orbitais p vizinhos.', 'Só num anel plano os seis orbitais p ficam paralelos entre si.', 'Torcer o anel diminui a sobreposição e a estabilização: a geometria plana é a de menor energia.'], answer: 'Para que os seis orbitais p sejam paralelos e se sobreponham continuamente.' },
  /* 2. Ressonância */
  { level: 'Ressonância', title: 'Kekulé A e B', q: 'As duas estruturas de Kekulé do benzeno representam moléculas diferentes em equilíbrio?', think: 'O que muda entre A e B?', hint: 'Átomos não se movem nas formas de ressonância.', steps: ['A e B têm os átomos nas mesmas posições: diferem só na distribuição dos elétrons π.', 'São <b>formas de ressonância</b>, não isômeros: não há equilíbrio nem "oscilação".', 'A molécula real é o <b>híbrido</b>, representado por um círculo no hexágono.'], solFig: RF(['benzeno', { cap: 'A' }], ['benzeno', { alt: true, cap: 'B' }], ['benzeno', { mode: 'hybrid', cap: 'híbrido' }]), answer: 'Não: são representações limite de uma única estrutura real (híbrido).' },
  { level: 'Ressonância', title: 'Ordem de ligação', q: 'Qual a ordem de ligação C–C do benzeno, considerando as duas formas de Kekulé?', think: 'Em A, uma dada ligação é dupla; em B, é simples.', hint: 'Média das duas formas equivalentes.', steps: ['Cada ligação C–C é dupla numa forma e simples na outra.', 'Como as formas são equivalentes, contribuem igualmente.', 'Ordem média = (2 + 1)/2 = <b>1,5</b>.'], answer: '1,5.' },
  { level: 'Ressonância', title: 'Setas de ressonância', q: 'Quantas setas curvas são necessárias para converter Kekulé A em B?', think: 'Cada seta move um par π.', hint: 'Há três ligações π.', steps: ['Cada par π move-se para a ligação vizinha.', 'Três pares π → <b>três setas</b>, todas no mesmo sentido.', 'Nenhuma ligação σ é rompida e nenhum átomo se move.'], answer: 'Três setas.' },
  /* 3. Orbitais p */
  { level: 'Orbitais p', title: 'Quantos orbitais p?', q: 'Quantos orbitais p participam do sistema π do benzeno e quantos orbitais moleculares π resultam?', think: 'Um p por carbono.', hint: 'n orbitais atômicos → n orbitais moleculares.', steps: ['Seis carbonos sp² → <b>seis orbitais p</b>.', 'Combinando 6 orbitais atômicos obtêm-se <b>6 orbitais moleculares π</b>: 3 ligantes e 3 antiligantes.', 'Os 6 elétrons π ocupam os 3 ligantes (camada fechada).'], answer: '6 orbitais p → 6 OM π (3 ligantes ocupados).' },
  { level: 'Orbitais p', title: 'Nuvem π', q: 'Descreva a distribuição da densidade π no benzeno.', think: 'Onde fica o plano nodal de um orbital p?', hint: 'O plano do anel.', steps: ['Cada orbital p tem plano nodal coincidente com o plano do anel.', 'A combinação em fase gera duas regiões contínuas em forma de anel: uma <b>acima</b> e outra <b>abaixo</b> do plano.', 'Essa nuvem rica em elétrons é atraída por eletrófilos — origem da reatividade frente a E⁺.'], answer: 'Dois "anéis" de densidade π acima e abaixo do plano molecular.' },
  /* 4. Estabilidade */
  { level: 'Estabilidade termodinâmica', title: 'Estável não é inerte', q: 'O benzeno é "estável". Isso significa que ele não reage?', think: 'Estabilidade termodinâmica × reatividade.', hint: 'Ele reage com eletrófilos fortes.', steps: ['Estabilidade aromática: o benzeno tem energia mais baixa que um polieno hipotético equivalente.', 'Ele <b>reage</b>, mas de forma a preservar essa estabilização: substituição eletrofílica (com catalisadores).', 'Também pode sofrer adição em condições severas (ex.: hidrogenação catalítica a alta pressão).'], answer: 'Não: reage, mas prefere caminhos que preservem a aromaticidade.' },
  { level: 'Estabilidade termodinâmica', title: 'Três eteno ≠ benzeno', q: 'Por que não é correto dizer que o benzeno equivale a "três alcenos"?', think: 'Quantos átomos compartilham cada par π?', hint: 'Localizado × deslocalizado.', steps: ['Num alceno, o par π fica entre dois carbonos.', 'No benzeno, os 6 elétrons π estão deslocalizados sobre os 6 carbonos num ciclo contínuo.', 'Por isso suas propriedades (comprimentos, energia, reatividade) diferem das de três C=C isoladas.'], answer: 'Os elétrons π do benzeno formam um único sistema cíclico deslocalizado.' },
  /* 5. Calor de hidrogenação */
  { level: 'Calor de hidrogenação', title: 'Estimativa da estabilização', q: 'ΔH(hidrogenação) do cicloexeno = −120 kJ/mol; do benzeno = −208 kJ/mol. Estime a estabilização aromática.', think: 'Qual seria o ΔH de um "ciclo-hexatrieno" sem estabilização?', hint: '3 × (−120).', steps: ['Esperado para 3 C=C independentes: 3 × (−120) = −360 kJ/mol.', 'Observado: −208 kJ/mol.', 'Diferença: 360 − 208 ≈ <b>150 kJ/mol</b> — o benzeno está ≈ 150 kJ/mol abaixo do esperado.'], answer: '≈ 150 kJ/mol (depende da referência adotada).' },
  { level: 'Calor de hidrogenação', title: 'Ciclo-hexa-1,3-dieno', q: 'O ΔH de hidrogenação do ciclo-hexa-1,3-dieno (≈ −232 kJ/mol) é próximo de 2 × (−120). O que isso indica?', think: 'Conjugação simples × aromaticidade.', hint: 'Compare as estabilizações.', steps: ['2 × (−120) = −240 kJ/mol; o observado é ≈ −232: estabilização de apenas ≈ 8 kJ/mol.', 'A conjugação de duas C=C num sistema aberto estabiliza pouco.', 'A grande estabilização do benzeno (≈ 150 kJ/mol) vem do sistema <b>cíclico</b> com 6 elétrons π — não só da conjugação.'], answer: 'Conjugação comum dá pouca estabilização; a aromaticidade dá muito mais.' },
  /* 6. Critérios */
  { level: 'Critérios de aromaticidade', title: 'Os quatro critérios', q: 'Liste os critérios para que um composto seja aromático.', think: 'Estrutura + contagem.', hint: 'Três estruturais e um eletrônico.', steps: ['<b>Cíclico</b>.', '<b>Planar</b> (ou capaz de ser planar).', '<b>Totalmente conjugado</b>: orbital p em todos os átomos do anel.', '<b>4n + 2 elétrons π</b> (regra de Hückel).'], answer: 'Cíclico, planar, conjugado, 4n+2 elétrons π.' },
  { level: 'Critérios de aromaticidade', title: 'Ciclopentadieno', q: 'O ciclopentadieno é aromático?', think: 'Verifique se todos os átomos do anel têm orbital p.', hint: 'Observe o CH₂.', steps: ['É cíclico e plano.', 'O CH₂ é <b>sp³</b>: não tem orbital p.', 'A conjugação cíclica é interrompida → <b>não aromático</b> (embora tenha 4 elétrons π).'], solFig: RF(['cpH', { badge: true }]), answer: 'Não aromático (C sp³ interrompe a conjugação).' },
  { level: 'Critérios de aromaticidade', title: 'Hexatrieno aberto', q: 'O hexa-1,3,5-trieno tem 6 elétrons π conjugados. É aromático?', think: 'Primeiro critério.', hint: 'É cíclico?', steps: ['Não é cíclico: a conjugação não fecha um ciclo.', 'A regra de Hückel não se aplica.', '<b>Não aromático</b>.'], answer: 'Não aromático (acíclico).' },
  /* 7. Hückel */
  { level: 'Hückel', title: 'Resolva para n', q: 'Para quais números de elétrons π (até 18) há n inteiro em 4n + 2?', think: 'n = 0, 1, 2…', hint: 'Substitua.', steps: ['n = 0 → 2; n = 1 → 6; n = 2 → 10; n = 3 → 14; n = 4 → 18.', 'Sequência: <b>2, 6, 10, 14, 18</b>.', 'Já 4, 8, 12, 16 são da forma 4n (padrão antiaromático, se plano e conjugado).'], answer: '2, 6, 10, 14, 18.' },
  { level: 'Hückel', title: 'Por que 4n+2?', q: 'Use o círculo de Frost para explicar por que 6 elétrons π dão estabilidade especial a um anel de 6 átomos.', think: 'Inscreva um hexágono com vértice para baixo.', hint: 'Conte os níveis ligantes.', steps: ['Níveis: 1 (mais baixo), 2 degenerados, 2 degenerados (antiligantes), 1 (mais alto).', '6 elétrons preenchem completamente os 3 OM ligantes: <b>camada fechada</b>.', 'Com 4 elétrons num anel de 4 (ciclobutadieno), sobram 2 elétrons desemparelhados em OM degenerados não ligantes → antiaromático.'], answer: '4n+2 preenche completamente os OM ligantes (camada fechada).' },
  { level: 'Hückel', title: 'Contagem não basta', q: 'O COT tem 8 elétrons π e a regra prevê 4n. Por que ele não é antiaromático?', think: 'Qual é a geometria do COT?', hint: 'Banheira.', steps: ['O COT adota conformação de <b>banheira</b> (não plana).', 'As C=C ficam em planos diferentes: os orbitais p vizinhos não são paralelos e a conjugação cíclica se perde.', 'Comporta-se como polieno: <b>não aromático</b>. Escapa da antiaromaticidade mudando de forma.'], solFig: RF(['cot', { badge: true }]), answer: 'É não planar (banheira) → não aromático.' },
  /* 8. Aromático/anti/não */
  { level: 'Aromático, antiaromático, não aromático', title: 'Ciclobutadieno', q: 'Classifique o ciclobutadieno.', think: 'Cíclico, plano, conjugado. Quantos elétrons π?', hint: '4 = 4n.', steps: ['Cíclico, plano, 4 C sp² com orbital p.', '4 elétrons π = 4(1): padrão 4n.', '<b>Antiaromático</b>: extremamente instável (isolável só a baixa temperatura em matriz); distorce-se para um retângulo.'], solFig: RF(['ciclobutadieno', { badge: true }]), answer: 'Antiaromático.' },
  { level: 'Aromático, antiaromático, não aromático', title: 'Mesmo número, classes diferentes', q: 'O diânion do COT (10 elétrons π) é plano e aromático; o COT (8 elétrons π) é não aromático. O que mudou?', think: 'Quantos elétrons e qual a geometria?', hint: '10 = 4(2)+2.', steps: ['Ao receber 2 elétrons, o sistema passa a 10 elétrons π = 4n+2.', 'Agora a forma plana é favorável: o anel planariza.', 'Plano + conjugado + 10 elétrons → <b>aromático</b>.'], solFig: RF(['cot', { badge: true }], ['cot2', { badge: true }]), answer: 'O número de elétrons π (e com ele a geometria preferida).' },
  /* 9. Íons */
  { level: 'Íons aromáticos', title: 'Cátion tropílio', q: 'O cátion cicloeptatrienílio (tropílio, C₇H₇⁺) é aromático?', think: 'Qual a hibridização do C⁺?', hint: 'O carbocátion é sp² com orbital p vazio.', steps: ['O C⁺ é sp², com orbital p <b>vazio</b>: o ciclo de orbitais p fica completo.', 'Elétrons π: 3 C=C × 2 = 6 (o p vazio contribui com 0).', '6 = 4(1)+2 → <b>aromático</b>. Por isso sais de tropílio são surpreendentemente estáveis.'], solFig: RF(['tropilio', { badge: true }]), answer: 'Aromático (6 elétrons π).' },
  { level: 'Íons aromáticos', title: 'Acidez do ciclopentadieno', q: 'Por que o ciclopentadieno (pKa ≈ 16) é muito mais ácido que um alcano (pKa ≈ 50)?', think: 'Analise a base conjugada.', hint: 'C₅H₅⁻.', steps: ['Ao perder H⁺, o CH₂ vira C⁻ com par em orbital p.', 'O ânion tem 5 orbitais p, plano e 6 elétrons π (4 + 2) → <b>aromático</b>.', 'A base conjugada é muito estabilizada → ácido muito mais forte.'], solFig: RF(['cpH', { badge: true }], ['cp', { badge: true }]), answer: 'A base conjugada (ciclopentadienila) é aromática.' },
  { level: 'Íons aromáticos', title: 'Cátion ciclopentadienila', q: 'Classifique o cátion ciclopentadienila (C₅H₅⁺).', think: 'O C⁺ tem p vazio.', hint: '2 C=C.', steps: ['5 orbitais p, plano, conjugado.', 'Elétrons π: 2 × 2 + 0 = 4 = 4(1).', '<b>Antiaromático</b> (muito instável).'], solFig: RF(['cpPlus', { badge: true }]), answer: 'Antiaromático (4 elétrons π).' },
  /* 10. Heteroaromáticos */
  { level: 'Heteroaromáticos', title: 'Piridina', q: 'O par isolado do N da piridina faz parte do sistema π?', think: 'O N já participa de uma C=N.', hint: 'Onde fica o par?', steps: ['O N está numa ligação dupla: é sp² e contribui com <b>1 elétron</b> para o orbital p.', 'O par isolado ocupa um orbital sp² no plano do anel, perpendicular ao sistema π.', 'Total π = 6 (aromático) <b>sem</b> o par; por isso o par fica disponível: a piridina é básica.'], solFig: RF(['piridina', { badge: true }]), answer: 'Não: o par fica em sp², no plano.' },
  { level: 'Heteroaromáticos', title: 'Pirrol', q: 'Por que o pirrol é muito menos básico que a piridina?', think: 'Onde está o par do N no pirrol?', hint: 'Conte os elétrons π sem e com o par.', steps: ['As duas C=C fornecem 4 elétrons π; faltam 2 para 6.', 'O par isolado do N ocupa o orbital p e completa o sexteto: <b>faz parte do sistema aromático</b>.', 'Protonar o N removeria esse par do sistema π e destruiria a aromaticidade → baixa basicidade.'], solFig: RF(['pirrol', { badge: true }]), answer: 'Seu par isolado é parte do sexteto aromático.' },
  { level: 'Heteroaromáticos', title: 'Furano', q: 'O O do furano tem dois pares isolados. Quantos participam do sistema π?', think: 'Um orbital p só comporta 2 elétrons.', hint: 'O O é descrito como sp².', steps: ['Um par ocupa o orbital p (paralelo aos dos C) → entra no sistema π.', 'O outro par fica num híbrido no plano do anel → fora do sistema π.', '4 + 2 = 6 elétrons π → aromático.'], solFig: RF(['furano', { badge: true }]), answer: 'Apenas um.' },
  /* 11. Policíclicos */
  { level: 'Sistemas policíclicos', title: 'Naftaleno', q: 'Quantos elétrons π tem o naftaleno? Ele satisfaz 4n+2?', think: 'Dez carbonos sp².', hint: '10 = 4(2)+2.', steps: ['10 carbonos sp², cada um com um orbital p: 10 elétrons π.', '10 = 4(2) + 2.', 'É plano e totalmente conjugado → aromático. (Para sistemas fundidos a regra é aplicada de forma qualitativa.)'], solFig: RF(['naftaleno', { mode: 'hybrid' }]), answer: '10 elétrons π; aromático.' },
  { level: 'Sistemas policíclicos', title: 'Antraceno e fenantreno', q: 'Antraceno e fenantreno são isômeros (C₁₄H₁₀). Quantos elétrons π cada um tem?', think: 'Conte os carbonos sp².', hint: '14 C.', steps: ['Ambos: 14 C sp² → 14 elétrons π = 4(3)+2.', 'Ambos são aromáticos, mas a estabilização por anel é menor que no benzeno.', 'Por isso o anel central do antraceno sofre adição com relativa facilidade (ex.: Diels–Alder, Br₂).'], solFig: RF(['antraceno', { mode: 'hybrid' }], ['fenantreno', { mode: 'hybrid' }]), answer: '14 elétrons π cada.' },
  /* 12. Substituição × adição */
  { level: 'Substituição versus adição', title: 'Por que não adição?', q: 'Por que o benzeno não sofre adição de Br₂ como o cicloexeno?', think: 'Compare os produtos.', hint: 'O produto de adição é aromático?', steps: ['A adição tornaria dois carbonos sp³: o produto (dibromo-ciclo-hexadieno) <b>não é aromático</b>.', 'Perderia ≈ 150 kJ/mol de estabilização: a adição é termodinamicamente desfavorável.', 'Na substituição, o produto (bromobenzeno) <b>continua aromático</b>.'], solFig: BZ({ kek: 'hyb', sub: 'Br' }), answer: 'Porque a adição destruiria a aromaticidade no produto.' },
  { level: 'Substituição versus adição', title: 'Papel do FeBr₃', q: 'Por que é necessário FeBr₃ na bromação do benzeno?', think: 'Br₂ sozinho é eletrófilo fraco para o benzeno.', hint: 'Ácido de Lewis.', steps: ['O benzeno é menos nucleofílico que um alceno: atacar o eletrófilo significa perder (temporariamente) a aromaticidade.', 'FeBr₃ coordena-se ao Br₂ (Br–Br–FeBr₃), polarizando a ligação e gerando um eletrófilo muito mais forte.', 'Assim a barreira da etapa lenta se torna acessível.'], answer: 'Ativa o Br₂, tornando-o eletrófilo suficientemente forte.' },
  /* 13. SEA */
  { level: 'Introdução à SEA', title: 'Complexo σ', q: 'O complexo σ (íon arênio) é aromático? Quantas formas de ressonância ele tem?', think: 'O carbono atacado tem orbital p?', hint: 'Ele é sp³.', steps: ['O carbono atacado fica sp³ (com H e E): o ciclo de orbitais p é interrompido → <b>não aromático</b>.', 'A carga + é deslocalizada em <b>três</b> formas: nos carbonos orto, para e orto ao C sp³.', 'É estabilizado por ressonância, mas é um intermediário de alta energia.'], solFig: AR('A'), answer: 'Não aromático; três formas de ressonância.' },
  { level: 'Introdução à SEA', title: 'Restauração da aromaticidade', q: 'Na segunda etapa da SEA, por que a base remove H⁺ em vez de o nucleófilo se adicionar ao carbocátion?', think: 'Compare os produtos das duas opções.', hint: 'Qual é aromático?', steps: ['Adição do nucleófilo → produto com C sp³: não aromático.', 'Perda de H⁺ do C sp³ → o par da C–H volta ao anel e restaura o sexteto aromático.', 'O produto de substituição é muito mais estável: a etapa 2 é rápida e favorável.'], solFig: BZ({ kek: 'hyb', sub: 'E' }), answer: 'A perda de H⁺ restaura a aromaticidade.' },
  { level: 'Introdução à SEA', title: 'Nitração', q: 'Qual é o eletrófilo na nitração do benzeno e como ele é gerado?', think: 'HNO₃ + H₂SO₄.', hint: 'Íon nitrônio.', steps: ['H₂SO₄ protona o HNO₃: H₂O⁺–NO₂.', 'Perda de água: <b>NO₂⁺</b> (íon nitrônio, linear, O=N⁺=O).', 'NO₂⁺ é atacado pelo anel → complexo σ → perda de H⁺ → nitrobenzeno.'], answer: 'NO₂⁺, gerado por HNO₃/H₂SO₄.' },
];

/* ===================================================================
 * Propostos
 * =================================================================== */
const mc = (title, q, o, e, fig) => ({ title, type: 'mc', q, o, a: 0, e, fig });
const tf = (title, items, e) => ({ title, type: 'tf', q: 'Marque V ou F:', items, e });
const dnd = (title, q, pairs, e) => ({ title, type: 'dnd', q, pairs, e });
const match = (title, q, pairs, e) => ({ title, type: 'match', q, pairs, e });
const err = (title, claim, o, e) => mc('Detecte o erro · ' + title, `Um estudante afirmou: <i>“${claim}”</i>. Qual é o erro?`, o, e);

export const PROPOSED = {
  easy: [
    mc('Hibridização', 'A hibridização dos carbonos do benzeno é:', ['sp²', 'sp³', 'sp', 'sp³d'], 'Três domínios σ.'),
    mc('Ângulo', 'O ângulo C–C–C no benzeno é:', ['120°', '109,5°', '180°', '90°'], 'Hexágono regular plano.'),
    mc('Comprimento', 'O comprimento C–C no benzeno (≈ 1,39 Å) é:', ['intermediário entre C–C e C=C', 'igual ao de C–C', 'igual ao de C=C', 'menor que o de C≡C'], 'Ordem ≈ 1,5.'),
    mc('Elétrons π', 'Quantos elétrons π tem o benzeno?', ['6', '3', '12', '4'], 'Três C=C × 2.', RF('benzeno')),
    mc('Hückel', 'Qual número satisfaz 4n + 2?', ['10', '8', '12', '4'], 'n = 2.'),
    mc('Hückel', 'Qual número corresponde a 4n?', ['8', '6', '10', '14'], 'n = 2.'),
    mc('Critérios', 'Qual NÃO é critério de aromaticidade?', ['ter heteroátomo', 'ser cíclico', 'ser planar', 'ter 4n+2 elétrons π'], 'Heteroátomo é opcional.'),
    mc('Classificação', 'O ciclobutadieno é:', ['antiaromático', 'aromático', 'não aromático', 'alifático saturado'], '4 elétrons π, plano, conjugado.', RF('ciclobutadieno')),
    mc('Classificação', 'O ciclopentadieno é:', ['não aromático', 'aromático', 'antiaromático', 'radical'], 'CH₂ sp³.', RF('cpH')),
    mc('Íons', 'O ânion ciclopentadienila tem quantos elétrons π?', ['6', '4', '5', '2'], '4 + 2 (par no p).', RF('cp')),
    mc('Íons', 'O cátion ciclopropenílio (C₃H₃⁺) tem:', ['2 elétrons π: aromático', '3 elétrons π: radical', '4 elétrons π: antiaromático', '0 elétron π'], 'n = 0.', RF('ciclopropenilio')),
    mc('Heteroaromáticos', 'Na piridina, o par isolado do N está:', ['num orbital sp² no plano do anel', 'no orbital p, no sistema π', 'num orbital s puro', 'deslocalizado no anel'], 'Fora do sexteto.', RF('piridina')),
    mc('Heteroaromáticos', 'No pirrol, o par isolado do N está:', ['no orbital p (sistema π)', 'num orbital sp² no plano', 'num orbital sp³', 'ligado ao H'], 'Completa o sexteto.', RF('pirrol')),
    mc('Policíclicos', 'O naftaleno tem quantos elétrons π?', ['10', '12', '8', '6'], '10 C sp².'),
    mc('Reatividade', 'Benzeno + Br₂/FeBr₃ produz principalmente:', ['bromobenzeno (substituição)', '1,2-dibromociclo-hexadieno (adição)', 'cicloexano', 'nenhuma reação'], 'SEA.'),
    mc('Reatividade', 'Cicloexeno + Br₂ produz:', ['trans-1,2-dibromocicloexano (adição)', 'bromocicloexeno (substituição)', 'benzeno', 'nada'], 'Alceno → adição.'),
    tf('Benzeno', [['O benzeno é planar.', 'V'], ['As ligações C–C do benzeno têm comprimentos alternados.', 'F'], ['O benzeno tem 6 orbitais p paralelos.', 'V'], ['As formas de Kekulé estão em equilíbrio químico.', 'F']], 'Deslocalização; ressonância não é equilíbrio.'),
    tf('Termos', [['Estabilidade aromática significa que o composto não reage.', 'F'], ['A estabilização do benzeno é ≈ 150 kJ/mol (estimativa).', 'V'], ['4n+2 com n = 0 dá 2 elétrons.', 'V']], 'Estável ≠ inerte.'),
    dnd('Molécula → classe', 'Associe cada molécula à sua classe:', [['benzeno', 'aromático'], ['ciclobutadieno', 'antiaromático'], ['ciclopentadieno', 'não aromático'], ['ânion ciclopentadienila', 'aromático'], ['COT', 'não aromático']], 'Critérios + contagem.'),
    dnd('Estrutura → nº π', 'Associe cada estrutura ao número de elétrons π:', [['ciclopropenílio', '2'], ['benzeno', '6'], ['COT', '8'], ['naftaleno', '10'], ['antraceno', '14']], 'Conte 2 por C=C, 2 por par em p, 0 por C⁺.'),
  ],
  mid: [
    mc('Tropílio', 'O cátion tropílio (C₇H₇⁺) é aromático porque:', ['o C⁺ tem p vazio, completando o ciclo, com 6 elétrons π', 'tem 7 elétrons π', 'é não planar', 'o C⁺ é sp³'], 'p vazio + 6 e.', RF('tropilio')),
    mc('Cicloeptatrieno', 'O cicloeptatrieno (C₇H₈) é:', ['não aromático (CH₂ sp³)', 'aromático', 'antiaromático', 'aromático só em solução'], 'Conjugação interrompida.', RF('cicloheptatrieno')),
    mc('Cp⁺', 'O cátion ciclopentadienila (C₅H₅⁺) é:', ['antiaromático (4 elétrons π)', 'aromático (6)', 'não aromático', 'aromático (4)'], '2 C=C + p vazio.', RF('cpPlus')),
    mc('Furano', 'Quantos elétrons π do O do furano participam do sistema aromático?', ['2', '4', '0', '1'], 'Um par no p; outro no plano.', RF('furano')),
    mc('Tiofeno', 'O tiofeno é aromático com:', ['6 elétrons π (4 das C=C + 2 do S)', '8 elétrons π', '4 elétrons π', '5 elétrons π'], 'Análogo ao furano.', RF('tiofeno')),
    mc('Pirimidina', 'Na pirimidina, os pares isolados dos dois N:', ['ficam no plano (tipo piridina), fora do sistema π', 'entram no sistema π', 'um entra e outro não', 'não existem'], 'Ambos N em C=N.', RF('pirimidina')),
    mc('Imidazol', 'No imidazol, qual N tem o par no sistema π?', ['o N–H (tipo pirrol)', 'o N= (tipo piridina)', 'ambos', 'nenhum'], 'N–H doa o par; N= é básico.', RF('imidazol')),
    mc('Hidrogenação', 'ΔH(cicloexeno) = −120 kJ/mol. O ΔH esperado para 3 C=C isoladas e o observado para o benzeno são:', ['−360 e −208 kJ/mol', '−360 e −360 kJ/mol', '−120 e −208 kJ/mol', '−240 e −120 kJ/mol'], 'Diferença ≈ 150.'),
    mc('Estabilização', 'A diferença entre o ΔH esperado e o observado para o benzeno mede:', ['a estabilização aromática', 'a energia de ativação', 'a entalpia de ligação C–H', 'a tensão de anel'], 'Termo preferível a "energia de ressonância".'),
    mc('Complexo σ', 'No complexo σ, o carbono atacado pelo eletrófilo é:', ['sp³', 'sp²', 'sp', 'carbocátion'], 'Ligado a H e E.', AR('A')),
    mc('Arênio', 'A carga + do íon arênio é deslocalizada em quais posições em relação ao C sp³?', ['orto e para', 'meta', 'apenas para', 'ipso'], 'Três formas.'),
    mc('Etapa lenta', 'Na SEA, a etapa geralmente determinante da velocidade é:', ['a formação do complexo σ', 'a perda de H⁺', 'a geração do H₂', 'a recombinação com Br⁻'], 'Perda temporária de aromaticidade.'),
    mc('Diânion do COT', 'O diânion do COT (C₈H₈²⁻) é:', ['aromático (10 elétrons π, plano)', 'antiaromático (8)', 'não aromático (banheira)', 'radical'], '10 = 4(2)+2.', RF('cot2')),
    match('Reação → eletrófilo', 'Associe cada SEA ao eletrófilo efetivo:', [['Nitração', 'NO₂⁺'], ['Acilação de Friedel–Crafts', 'R–C≡O⁺'], ['Alquilação de Friedel–Crafts', 'R⁺'], ['Bromação', 'Br₂···FeBr₃'], ['Sulfonação', 'SO₃']], 'Eletrófilos gerados pelos reagentes.'),
    dnd('Critério → atendido?', 'Para o ciclopentadieno, cada critério é atendido?', [['cíclico', 'sim'], ['planar', 'sim'], ['orbital p em todos os átomos', 'não'], ['4n+2 elétrons π', 'não']], 'CH₂ sp³; 4 elétrons π.'),
    dnd('Heteroátomo → par', 'Associe o heteroátomo ao papel do par isolado:', [['N da piridina', 'no plano (sp²)'], ['N do pirrol', 'no sistema π'], ['N–H do imidazol', 'no sistema π'], ['N= do imidazol', 'no plano (sp²)']], 'N= (em C=N) → par no plano; N–H → par no p.'),
    dnd('Reação → tipo', 'Classifique cada reação:', [['cicloexeno + Br₂', 'adição'], ['benzeno + Br₂/FeBr₃', 'substituição'], ['benzeno + HNO₃/H₂SO₄', 'substituição'], ['eteno + HBr', 'adição']], 'Alcenos: adição; benzeno: SEA.'),
    tf('Aromaticidade', [['Todo composto com 6 elétrons π é aromático.', 'F'], ['Um anel com um C sp³ não pode ser aromático (monocíclico).', 'V'], ['A piridina é mais básica que o pirrol.', 'V'], ['O COT é plano.', 'F']], 'Contagem não basta.'),
    tf('SEA', [['O complexo σ é aromático.', 'F'], ['A perda de H⁺ restaura a aromaticidade.', 'V'], ['FeBr₃ atua como ácido de Lewis.', 'V'], ['A sulfonação é reversível.', 'V']], 'Ver módulo 17–19.'),
    { title: 'Ordene', type: 'order', q: 'Ordene do MAIOR para o MENOR calor de hidrogenação liberado (em módulo):', items: [['t', '"ciclo-hexatrieno" hipotético'], ['d', 'ciclo-hexa-1,3-dieno'], ['b', 'benzeno'], ['e', 'cicloexeno']].map(([id, label]) => ({ id, label })), correct: ['t', 'd', 'b', 'e'], top: 'mais exotérmico', bottom: 'menos exotérmico', explain: '360 > 232 > 208 > 120 kJ/mol.', e: '360 > 232 > 208 > 120 kJ/mol.' },
  ],
  hard: [
    err('Kekulé', 'O benzeno alterna rapidamente entre duas estruturas com três duplas fixas.', ['Ressonância não é alternância: a molécula real é um único híbrido com elétrons deslocalizados', 'O benzeno tem quatro duplas', 'As duplas são fixas, mas não alternam', 'Não há erro'], 'Formas de ressonância não existem separadamente.'),
    err('Hückel', 'Todo composto com 6 elétrons π é aromático.', ['Também é preciso ser cíclico, planar e totalmente conjugado', '6 não é 4n+2', 'Só compostos com N são aromáticos', 'Não há erro'], 'Ex.: hexatrieno (acíclico) tem 6 e π e não é aromático.'),
    err('COT', 'O COT é antiaromático porque tem 8 elétrons π.', ['O COT não é plano (banheira): é não aromático', '8 é 4n+2', 'O COT tem 6 elétrons π', 'Não há erro'], 'Escapa da antiaromaticidade dobrando-se.'),
    err('Piridina', 'O par isolado do N da piridina faz parte do sexteto aromático.', ['O par fica em sp², no plano; o N contribui com 1 elétron π', 'A piridina não é aromática', 'O par fica num orbital s', 'Não há erro'], 'Por isso a piridina é básica.'),
    err('Pirrol', 'O pirrol é fortemente básico porque tem um par isolado no N.', ['O par do N está no sistema π; protoná-lo destruiria a aromaticidade', 'O pirrol não tem par isolado', 'O N do pirrol é sp³', 'Não há erro'], 'Baixa basicidade.'),
    err('SEA', 'Compostos aromáticos só sofrem substituição, nunca adição.', ['Adições são possíveis em condições severas (ex.: hidrogenação catalítica, adições radicalares)', 'Aromáticos não reagem', 'Aromáticos só sofrem adição', 'Não há erro'], 'Evite afirmações absolutas.'),
    err('Complexo σ', 'O complexo σ é aromático porque tem carga deslocalizada.', ['Tem um C sp³: o ciclo de orbitais p é interrompido → não aromático', 'O complexo σ não tem carga', 'A carga fica só no carbono meta', 'Não há erro'], 'Deslocalização ≠ aromaticidade.'),
    err('Ciclopentadieno', 'O ciclopentadieno é aromático por ter duas duplas conjugadas num anel.', ['O CH₂ é sp³ e interrompe a conjugação cíclica; só o ânion é aromático', 'Tem 6 elétrons π', 'Não é cíclico', 'Não há erro'], 'Conjugação cíclica contínua é necessária.'),
    mc('Oxazol', 'O oxazol (anel de 5 com O e N=) é aromático. Quantos elétrons π cada heteroátomo contribui?', ['O: 2; N: 1', 'O: 1; N: 2', 'O: 2; N: 2', 'O: 0; N: 1'], 'O tipo furano; N tipo piridina. Total 6.', RF(D.oxazol)),
    mc('C₉H₉⁻', 'O ânion ciclononatetraenila (C₉H₉⁻), se plano, teria quantos elétrons π e qual classificação?', ['10, aromático', '9, radical', '8, antiaromático', '10, antiaromático'], '4 C=C + par no C⁻ = 10 = 4(2)+2.', RF(D.ciclononatetraenila)),
    mc('Ciclo-hexa-1,4-dieno', 'O ciclo-hexa-1,4-dieno é:', ['não aromático: dois CH₂ sp³ interrompem a conjugação', 'aromático', 'antiaromático', 'aromático só como diânion'], 'Duplas isoladas.', RF(D.cicloexadieno14)),
    mc('Acidez', 'Qual é mais ácido: cicloeptatrieno ou ciclopentadieno? Por quê?', ['ciclopentadieno: a base conjugada (6 e π) é aromática; a do cicloeptatrieno (8 e π) não', 'cicloeptatrieno: o ânion tem 8 e π', 'iguais', 'nenhum é ácido'], 'C₇H₇⁻ seria 4n (antiaromático se plano).'),
    mc('Halogeneto de tropílio', 'O brometo de cicloeptatrienila (C₇H₇Br) é solúvel em água e se comporta como sal. Explicação:', ['ioniza facilmente formando o cátion tropílio aromático', 'forma um ânion aromático', 'é um alcano', 'o Br é aromático'], 'C₇H₇⁺ Br⁻.'),
    mc('Energia', 'No diagrama de energia da SEA, comparado com adição ao complexo σ, a perda de H⁺:', ['leva a um produto muito mais baixo em energia (aromático)', 'leva a um produto mais alto', 'não altera a energia', 'exige um catalisador extra'], 'Restauração da aromaticidade.'),
    mc('Friedel–Crafts', 'Por que a acilação de Friedel–Crafts não sofre rearranjos e tende à monoacilação?', ['o íon acílio é estabilizado por ressonância e o produto (cetona) desativa o anel', 'o AlCl₃ impede rearranjos', 'o acílio é um radical', 'o benzeno não reage com acílio'], 'R–C≡O⁺.'),
    mc('Antraceno', 'O anel central do antraceno sofre adição (ex.: Br₂, Diels–Alder) com relativa facilidade porque:', ['o produto ainda mantém dois anéis benzênicos aromáticos', 'o antraceno é antiaromático', 'o antraceno não é plano', 'o anel central é sp³'], 'A perda de estabilização é parcial.'),
    mc('Frost', 'Num anel de 4 átomos com 4 elétrons π (plano), o círculo de Frost prevê:', ['2 elétrons desemparelhados em OM não ligantes degenerados', 'camada fechada', 'todos em OM antiligantes', '1 elétron desemparelhado'], 'Instabilidade (antiaromático).'),
    mc('Densidade π', 'Comparando com o benzeno, o anel da piridina é:', ['π-deficiente (N retira densidade)', 'π-excedente', 'igual', 'não aromático'], 'Pirrol é π-excedente.'),
    dnd('Contagem π', 'Associe cada espécie ao seu número de elétrons π:', [['pirrol', '6'], ['ciclobutadieno', '4'], ['diânion do COT', '10'], ['cátion Cp⁺', '4'], ['ciclopropenílio', '2']], 'Regras de contagem.'),
    { title: 'Ordene as etapas', type: 'order', q: 'Ordene as etapas da SEA (bromação):', items: [['a', 'Br₂ + FeBr₃ → Br₂···FeBr₃ (eletrófilo ativado)'], ['b', 'elétrons π atacam o Br (etapa lenta)'], ['c', 'complexo σ (perda temporária de aromaticidade)'], ['d', 'base remove H⁺ do C sp³'], ['e', 'bromobenzeno aromático + HBr + FeBr₃']].map(([id, label]) => ({ id, label })), correct: ['a', 'b', 'c', 'd', 'e'], top: 'início', bottom: 'fim', explain: 'Ativação → ataque → complexo σ → desprotonação → produto.', e: 'Ativação → ataque → complexo σ → desprotonação → produto.' },
  ],
};
