/*
 * exdata.js — exercícios resolvidos (8 níveis) e propostos (15/20/15).
 * Figuras geradas a partir da mesma geometria usada no 3D.
 */
import { ROTORS } from './conf.js';
import { newmanData, newmanSVG, sawhorseSVG, chairSVG } from './draw.js';

const nm = (k, phi, dir, cap) => ({ svg: () => newmanSVG(newmanData(ROTORS[k], phi, dir || 'fwd'), { maxw: 190, fs: 13 }), cap });
const sw = (k, phi, cap) => ({ svg: () => sawhorseSVG(ROTORS[k], phi, { maxw: 240, fs: 13 }), cap });
const ch = (subs, u, cap) => ({ svg: () => chairSVG(subs, u, { scale: 38 }), cap });
const chH = (u, cap) => ({ svg: () => chairSVG({}, u, { scale: 40, H: true, color: true, num: true }), cap });

const L1 = 'Nível 1 · Conceitos básicos', L2 = 'Nível 2 · Newman', L3 = 'Nível 3 · Cavalete', L4 = 'Nível 4 · Energia conformacional', L5 = 'Nível 5 · Cadeira', L6 = 'Nível 6 · Inversão (flip)', L7 = 'Nível 7 · Ciclo-hexanos substituídos', L8 = 'Nível 8 · Estabilidade';
export const SOLVED = [
  { level: L1, title: 'Conformação ou configuração?', q: 'Classifique cada par: (a) etano alternado × etano eclipsado; (b) cis- × trans-1,2-dimetilciclo-hexano; (c) butano anti × butano gauche.', think: 'Para interconverter, basta girar ligações simples, ou é preciso quebrar ligações?', hint: 'Em anéis, a rotação completa em torno de uma ligação C–C do anel é impossível.', steps: ['(a) Girar 60° em torno da C–C → mesma molécula: <b>conformações</b>.', '(b) Para passar de cis a trans seria preciso quebrar e refazer ligações (um grupo trocaria de face): <b>configurações diferentes</b> (estereoisômeros).', '(c) Rotação em torno de C2–C3: <b>conformações</b>.'], answer: 'conformações; configurações; conformações.' },
  { level: L1, title: 'Ângulo diedro no etano', q: 'Quais são os ângulos diedros H–C–C–H nas conformações alternada e eclipsada do etano?', think: 'Na Newman, os H da frente e de trás ficam a 120° entre si em cada carbono.', hint: 'Meça o menor ângulo entre um H da frente e o H de trás mais próximo.', steps: ['Eclipsada: cada H da frente cobre um H de trás → diedro <b>0°</b> (e 120°, 240° com os outros).', 'Alternada: cada H de trás fica entre dois da frente → diedros <b>60°</b> e 180°.'], answer: '0° (eclipsada) e 60°/180° (alternada).', fig: [nm('etano', 0, 'fwd', 'eclipsada'), nm('etano', 60, 'fwd', 'alternada')] },
  { level: L1, title: 'Barreira do etano', q: 'A diferença entre a eclipsada e a alternada do etano é ≈ 12 kJ/mol. Quanto "custa" cada par H/H eclipsado?', think: 'Quantos pares de C–H ficam eclipsados?', hint: 'Três pares.', steps: ['Na eclipsada há <b>3</b> pares H/H eclipsados.', '12 kJ/mol ÷ 3 ≈ <b>4 kJ/mol</b> por par (tensão torsional).', 'A barreira é pequena: à temperatura ambiente o etano gira milhões de vezes por segundo.'], answer: '≈ 4 kJ/mol por par H/H eclipsado.' },
  { level: L2, title: 'Do cavalete para a Newman', q: 'Converta o cavalete do butano (C2–C3) em projeção de Newman olhando de C2 para C3.', fig: sw('butano', 180, 'butano, cavalete'), think: 'O carbono da frente é o de baixo/à esquerda no cavalete.', hint: 'Os dois CH₃ estão em lados opostos.', steps: ['C2 (frente) vira o ponto: CH₃ para cima, dois H a 120°.', 'C3 (trás) vira o círculo; o CH₃ de C3 aponta para baixo.', 'CH₃/CH₃ a 180°: conformação <b>anti</b>.'], answer: 'Newman anti.', solFig: nm('butano', 180) },
  { level: L2, title: '2-Metilbutano (C2–C3)', q: 'Desenhe as três conformações alternadas do 2-metilbutano ao longo de C2–C3 e indique a mais estável.', think: 'C2 tem dois CH₃ e um H; C3 tem um CH₃ (o C4) e dois H.', hint: 'Conte as interações gauche CH₃/CH₃ em cada uma.', steps: ['C2 (frente): CH₃, CH₃, H. C3 (trás): CH₃, H, H.', 'Se o CH₃ de trás fica entre os dois CH₃ da frente: <b>duas</b> interações gauche.', 'Se fica anti a um CH₃ (e entre CH₃ e H): <b>uma</b> interação gauche (duas conformações equivalentes).', 'Mais estável: o CH₃ de C3 anti a um CH₃ de C2 (uma interação gauche, ≈ 3,8 kJ/mol).'], answer: 'conformações com uma única interação gauche.', solFig: [nm('metilbutano', 60, 'fwd', 'uma gauche'), nm('metilbutano', 300, 'fwd', 'duas gauche'), nm('metilbutano', 180, 'fwd', 'uma gauche')] },
  { level: L2, title: 'Mudando a direção de visualização', q: 'A Newman do butano anti foi desenhada olhando C2 → C3. Como fica olhando C3 → C2?', think: 'O carbono que era de trás passa a ser o da frente; a figura é vista "do outro lado".', hint: 'Imagine dar a volta na molécula: esquerda e direita se invertem.', steps: ['C3 vira o ponto (frente) e C2 o círculo.', 'A imagem é espelhada da esquerda para a direita (o eixo vertical se mantém).', 'No caso anti a figura parece igual, mas em conformações gauche o lado do CH₃ muda.'], answer: 'C3 na frente; figura espelhada.', fig: [nm('butano', 60, 'fwd', 'gauche, C2 → C3'), nm('butano', 60, 'rev', 'mesma conformação, C3 → C2')] },
  { level: L2, title: '3-Metilpentano', q: 'Para o 3-metilpentano olhando C2 → C3, quais grupos estão em cada carbono?', think: 'C2 = CH₂ ligado a C1; C3 = CH ligado a C4 (etila), a uma metila e a H.', hint: 'C2: CH₃, H, H. C3: CH₂CH₃, CH₃, H.', steps: ['Carbono da frente (C2): <b>CH₃ (C1), H, H</b>.', 'Carbono de trás (C3): <b>CH₂CH₃, CH₃, H</b>.', 'A mais estável coloca o CH₃ de C2 anti à etila (o grupo maior) e gauche ao CH₃.'], answer: 'frente: CH₃, H, H; trás: Et, CH₃, H.', solFig: nm('metilpentano', 180, 'fwd', 'CH₃ anti ao Et') },
  { level: L3, title: 'Newman → cavalete', q: 'Converta a Newman (butano gauche) em cavalete.', fig: nm('butano', 60), think: 'Incline a ligação C–C: o carbono da frente fica embaixo à esquerda.', hint: 'Mantenha os ângulos relativos: os grupos que estão "em cima" na Newman continuam em cima.', steps: ['Desenhe a ligação C2–C3 inclinada (C2 embaixo à esquerda).', 'Coloque os substituintes de C2 com o CH₃ para cima.', 'Coloque os de C3 com o CH₃ a 60° do CH₃ de C2.'], answer: 'cavalete gauche.', solFig: sw('butano', 60) },
  { level: L3, title: 'Cavalete → Newman', q: 'Qual a conformação deste cavalete do butano?', fig: sw('butano', 0), think: 'Os CH₃ estão no mesmo lado e alinhados?', hint: 'Projete ao longo da ligação.', steps: ['Olhando ao longo de C2–C3, o CH₃ de trás fica exatamente atrás do CH₃ da frente.', 'Diedro 0°: <b>totalmente eclipsada</b> — a conformação de maior energia do butano.'], answer: 'totalmente eclipsada (0°).', solFig: nm('butano', 0) },
  { level: L3, title: 'Mesma molécula?', q: 'Um cavalete do butano com os CH₃ a 180° e uma Newman anti representam a mesma conformação?', think: 'Newman e cavalete são apenas pontos de vista diferentes.', hint: 'Compare os diedros.', steps: ['Os dois mostram diedro CH₃/CH₃ = 180°.', 'São a <b>mesma conformação</b> desenhada de formas diferentes; nenhuma ligação muda.'], answer: 'Sim.' },
  { level: L4, title: 'Ordene as energias do butano', q: 'Ordene: anti, gauche, eclipsada (CH₃/H), totalmente eclipsada.', think: 'Alternadas < eclipsadas; grupos grandes próximos aumentam a energia.', hint: 'Valores ≈ 0; 3,8; 16; 19 kJ/mol.', steps: ['anti (0) < gauche (≈ 3,8) < eclipsada CH₃/H (≈ 16) < totalmente eclipsada (≈ 19).'], answer: 'anti < gauche < eclipsada < totalmente eclipsada.' },
  { level: L4, title: 'De onde vem a energia da totalmente eclipsada?', q: 'Explique os ≈ 19 kJ/mol da conformação totalmente eclipsada do butano.', think: 'Quais pares estão eclipsados?', hint: 'Um CH₃/CH₃ e dois H/H.', steps: ['Dois pares H/H eclipsados: 2 × 4 = 8 kJ/mol (torsional).', 'Um par CH₃/CH₃ eclipsado: ≈ 11 kJ/mol (torsional + estérica).', 'Total ≈ 19 kJ/mol.'], answer: '8 + 11 ≈ 19 kJ/mol.' },
  { level: L4, title: 'Por que gauche > anti?', q: 'Ambas são alternadas. Por que a gauche tem maior energia?', think: 'Qual a distância entre os CH₃?', hint: 'Tensão estérica, não torsional.', steps: ['Na gauche (60°), os CH₃ ficam próximos: suas nuvens se repelem (<b>tensão estérica</b>).', 'Na anti (180°), ficam o mais longe possível.', 'Diferença ≈ 3,8 kJ/mol; à temperatura ambiente há ≈ 70% anti.'], answer: 'interação estérica gauche.' },
  { level: L4, title: 'Conformações de mesma energia', q: 'No butano, quais ângulos dão conformações de mesma energia?', think: 'O perfil é simétrico em torno de 180°.', hint: '60° e 300°; 120° e 240°.', steps: ['60° e 300°: as duas gauche (imagens especulares).', '120° e 240°: as duas eclipsadas CH₃/H.', '0° e 360°: a mesma totalmente eclipsada.'], answer: '60°/300° e 120°/240°.' },
  { level: L5, title: 'Quantas posições?', q: 'Quantas ligações C–H axiais e equatoriais há no ciclo-hexano em cadeira?', fig: chH(0, 'cadeira: azul = axial, âmbar = equatorial'), think: 'Cada carbono tem uma de cada.', hint: '6 carbonos.', steps: ['Cada carbono: <b>1 axial + 1 equatorial</b>.', 'Total: 6 axiais e 6 equatoriais.', 'Axiais: paralelas ao eixo, alternando para cima e para baixo; equatoriais: ao redor do "equador".'], answer: '6 axiais e 6 equatoriais.' },
  { level: L5, title: 'Axiais para cima', q: 'Na cadeira com o C1 "para cima", quais carbonos têm H axial para cima?', think: 'Os axiais alternam.', hint: 'Carbonos alternados.', steps: ['C1: axial para cima.', 'C2: axial para baixo; C3: para cima; C4: para baixo; C5: para cima; C6: para baixo.', 'Axiais para cima: <b>C1, C3 e C5</b>.'], answer: 'C1, C3, C5.' },
  { level: L5, title: 'Up/down × axial/equatorial', q: 'No C2 da cadeira acima, qual H é "up" e qual é axial?', think: 'São classificações independentes.', hint: 'No C2 o axial aponta para baixo.', steps: ['No C2, o H <b>axial</b> aponta para <b>baixo</b> (down).', 'Logo o H <b>up</b> do C2 é o <b>equatorial</b> (levemente para cima).', 'Uma posição pode ser axial up, axial down, equatorial up ou equatorial down.'], answer: 'equatorial = up; axial = down.' },
  { level: L6, title: 'Flip do metilciclo-hexano', q: 'O CH₃ está axial (up) em C1. O que acontece após o flip?', fig: ch({ '1u': 'CH3' }, 0, 'CH₃ axial up'), think: 'O que muda e o que não muda no flip?', hint: 'axial ↔ equatorial; up permanece up.', steps: ['No flip, todas as posições axiais viram equatoriais e vice-versa.', 'A face do anel (up/down) <b>não</b> muda.', 'CH₃ passa a <b>equatorial up</b>.'], answer: 'equatorial, ainda up.', solFig: ch({ '1u': 'CH3' }, 1, 'após o flip') },
  { level: L6, title: 'Flip em C2', q: 'Um Cl equatorial down em C2. Após o flip?', think: 'Mesmas regras.', hint: 'down continua down.', steps: ['equatorial → <b>axial</b>.', 'down → <b>down</b>.', 'No C2, axial aponta para baixo: coerente.'], answer: 'axial down.' },
  { level: L6, title: 'O que o flip não faz', q: 'O flip transforma o cis-1,2-dimetilciclo-hexano em trans?', think: 'O flip quebra ligações?', hint: 'cis/trans depende de up/down.', steps: ['O flip só gira ligações simples (é conformacional).', 'up/down não muda → a relação cis/trans é mantida.', 'Logo o cis continua cis: só trocam axial/equatorial.'], answer: 'Não.' },
  { level: L7, title: 'cis-1,2-dimetil', q: 'Analise as duas cadeiras do cis-1,2-dimetilciclo-hexano.', fig: [ch({ '1u': 'CH3', '2u': 'CH3' }, 0, 'A'), ch({ '1u': 'CH3', '2u': 'CH3' }, 1, 'B')], think: 'cis = ambos up.', hint: 'C1 up = axial; C2 up = equatorial.', steps: ['Cadeira A: C1 axial, C2 equatorial (a,e).', 'Cadeira B: C1 equatorial, C2 axial (e,a).', 'Cada uma tem um CH₃ axial: <b>mesma energia</b>.'], answer: 'a,e ⇌ e,a (iguais).' },
  { level: L7, title: 'trans-1,2-dimetil', q: 'Analise o trans-1,2-dimetilciclo-hexano.', fig: [ch({ '1u': 'CH3', '2d': 'CH3' }, 0, 'A'), ch({ '1u': 'CH3', '2d': 'CH3' }, 1, 'B')], think: 'trans = um up e outro down.', hint: 'C2 down = axial na cadeira A.', steps: ['A: os dois axiais (a,a): 2 × 7,3 kJ/mol de interações 1,3-diaxiais.', 'B: os dois equatoriais (e,e): só uma interação gauche entre os CH₃ (≈ 3,8).', 'Predomina a <b>diequatorial</b>.'], answer: 'B (e,e).' },
  { level: L7, title: 'cis-1,3-dimetil', q: 'Analise o cis-1,3-dimetilciclo-hexano.', fig: [ch({ '1u': 'CH3', '3u': 'CH3' }, 0, 'A'), ch({ '1u': 'CH3', '3u': 'CH3' }, 1, 'B')], think: 'C1 e C3 têm axial up.', hint: 'cis-1,3 pode ser diequatorial.', steps: ['A: os dois axiais up, além disso um de frente para o outro (forte 1,3-diaxial).', 'B: diequatorial.', 'Predomina a <b>B</b>.'], answer: 'diequatorial (B).' },
  { level: L7, title: '1,4-dimetil cis × trans', q: 'Qual isômero do 1,4-dimetilciclo-hexano pode ser diequatorial?', think: 'C1 up = axial; C4 up = equatorial.', hint: 'Teste trans (1 up, 4 down).', steps: ['cis-1,4 (ambos up): a,e ⇌ e,a — sempre um axial.', 'trans-1,4 (up/down): a,a ⇌ <b>e,e</b>.', 'O <b>trans</b> pode ser diequatorial (por isso é o mais estável dos dois).'], answer: 'trans-1,4.' },
  { level: L8, title: 'Metilciclo-hexano', q: 'Qual a porcentagem aproximada da cadeira com CH₃ equatorial a 25 °C (valor A ≈ 7,3 kJ/mol)?', think: 'K = e^(ΔG/RT).', hint: 'RT ≈ 2,48 kJ/mol.', steps: ['K = e^(7,3/2,48) ≈ 19.', 'Fração equatorial = 19/20 ≈ <b>95%</b>.'], answer: '≈ 95% equatorial.' },
  { level: L8, title: 'cis-1-terc-butil-4-metil', q: 'Qual cadeira predomina no cis-1-terc-butil-4-metilciclo-hexano?', fig: [ch({ '1u': 'tBu', '4u': 'CH3' }, 0, 'A'), ch({ '1u': 'tBu', '4u': 'CH3' }, 1, 'B')], think: 'cis-1,4 é sempre (a,e).', hint: 'Quem deve ficar equatorial?', steps: ['Um dos grupos precisa ser axial.', 't-Bu axial custaria ≈ 21 kJ/mol; CH₃ axial ≈ 7,3.', 'Predomina a cadeira com <b>t-Bu equatorial</b> e CH₃ axial (cadeira B).'], answer: 't-Bu equatorial, CH₃ axial.' },
  { level: L8, title: 'trans-1-terc-butil-3-metil', q: 'Analise o trans-1-terc-butil-3-metilciclo-hexano.', fig: [ch({ '1u': 'tBu', '3d': 'CH3' }, 0, 'A'), ch({ '1u': 'tBu', '3d': 'CH3' }, 1, 'B')], think: 'trans-1,3 é (a,e).', hint: 'O t-Bu "trava" a cadeira.', steps: ['A: t-Bu axial, CH₃ equatorial (muito desfavorável).', 'B: t-Bu equatorial, CH₃ axial.', 'Predomina <b>B</b>: o t-Bu funciona como trava conformacional.'], answer: 'B.' },
  { level: L8, title: 'Isopropil × metil', q: 'No cis-1-isopropil-3-metilciclo-hexano, qual conformação predomina?', think: 'cis-1,3: (a,a) ⇌ (e,e).', hint: 'Diequatorial disponível.', steps: ['Cadeira (a,a): dois grupos axiais na mesma face, além de 1,3-diaxial entre eles.', 'Cadeira (e,e): nenhum grupo axial.', 'Predomina a <b>diequatorial</b>.'], answer: 'diequatorial.' },
];

/* ===================================================================
 * Propostos
 * =================================================================== */
const so = (x, t) => Object.assign({ t }, x);
const easy = [
  { title: 'Definição', type: 'mc', q: 'Conformações diferem por:', o: ['rotação em torno de ligações simples', 'quebra de ligações', 'troca de átomos', 'ligações duplas'], a: 0, e: 'Interconvertem-se sem quebrar ligações.' },
  { title: 'Diedro', type: 'mc', q: 'O ângulo diedro é o ângulo entre:', o: ['os planos A–B–C e B–C–D', 'as ligações A–B e C–D no plano', 'dois átomos de H', 'o eixo C–C e um H'], a: 0, e: 'Visto ao longo de B–C.' },
  { title: 'Etano', type: 'mc', q: 'No etano, a conformação de menor energia é:', o: ['alternada (60°)', 'eclipsada (0°)', 'qualquer uma', 'a de 30°'], a: 0, e: 'Menor tensão torsional.' },
  { title: 'Newman', type: 'mc', q: 'Na projeção de Newman, o carbono da frente é representado por:', o: ['um ponto', 'um círculo', 'um traço', 'um triângulo'], a: 0, e: 'O de trás é o círculo.' },
  { title: 'Máximos do etano', type: 'mc', q: 'Os máximos de energia do etano estão em:', o: ['0°, 120°, 240°', '60°, 180°, 300°', '90° e 270°', '180°'], a: 0, e: 'Eclipsadas.' },
  { title: 'Nome', type: 'mc', struct: true, q: 'Qual projeção mostra o butano <b>anti</b>?', o: [so(nm('butano', 180), ''), so(nm('butano', 60), ''), so(nm('butano', 0), ''), so(nm('butano', 120), '')], a: 0, e: 'CH₃ a 180°.' },
  { title: 'Gauche', type: 'mc', q: 'Na conformação gauche do butano, o diedro CH₃–C–C–CH₃ vale:', o: ['60°', '0°', '120°', '180°'], a: 0, e: 'Alternada com os CH₃ próximos.' },
  { title: 'Associe', type: 'match', q: 'Conformação → diedro CH₃/CH₃ (butano).', pairs: [['anti', '180°'], ['gauche', '60°'], ['eclipsada (CH₃/H)', '120°'], ['totalmente eclipsada', '0°']], e: 'Gire a ligação no módulo Butano.' },
  { title: 'Tensões', type: 'match', q: 'Associe.', pairs: [['tensão torsional', 'ligações eclipsadas'], ['tensão estérica', 'grupos volumosos próximos'], ['tensão angular', 'ângulos afastados de 109,5°']], e: 'Três origens diferentes de instabilidade.' },
  { title: 'Ciclopropano', type: 'mc', q: 'O ângulo C–C–C do ciclopropano é:', o: ['60°', '90°', '109,5°', '120°'], a: 0, e: 'Grande tensão angular.' },
  { title: 'Cadeira', type: 'mc', q: 'A conformação mais estável do ciclo-hexano é:', o: ['cadeira', 'barco', 'meia-cadeira', 'plana'], a: 0, e: 'Ângulos ≈ 111° e tudo alternado.' },
  { title: 'Posições', type: 'mc', q: 'Quantas posições axiais há no ciclo-hexano?', o: ['6', '3', '12', '2'], a: 0, e: '6 axiais + 6 equatoriais.' },
  { title: 'Valor A', type: 'mc', q: 'Qual grupo tem maior preferência equatorial?', o: ['t-butila', 'metila', 'cloro', 'hidroxila'], a: 0, e: 'Valor A ≈ 21 kJ/mol.' },
  { title: 'Verdadeiro ou falso', type: 'tf', q: 'Sobre o flip:', items: [['Axial vira equatorial.', 'V'], ['Up vira down.', 'F'], ['cis vira trans.', 'F'], ['Passa pela meia-cadeira.', 'V']], e: 'Só axial/equatorial muda.' },
  { title: 'Cis/trans', type: 'mc', q: 'Em cicloexanos, "cis" significa:', o: ['os dois grupos na mesma face (ambos up ou ambos down)', 'os dois axiais', 'os dois equatoriais', 'grupos em carbonos vizinhos'], a: 0, e: 'cis/trans ≠ axial/equatorial.' },
];
const mid = [
  { title: 'Ordene', type: 'order', q: 'Ordene as conformações do butano da <b>menor</b> para a <b>maior</b> energia.', items: [{ id: 'a', label: 'anti' }, { id: 'g', label: 'gauche' }, { id: 'e', label: 'eclipsada CH₃/H' }, { id: 't', label: 'totalmente eclipsada' }], correct: ['a', 'g', 'e', 't'], top: 'menor energia', bottom: 'maior energia', explain: '0 < 3,8 < 16 < 19 kJ/mol (aprox.).' },
  { title: 'Cavalete → nome', type: 'mc', q: 'Qual é a conformação deste cavalete do butano?', fig: sw('butano', 60), o: ['gauche', 'anti', 'eclipsada', 'totalmente eclipsada'], a: 0, e: 'CH₃ a 60°.' },
  { title: 'Newman do cavalete', type: 'mc', struct: true, q: 'Qual Newman (C2 → C3) corresponde ao cavalete?', fig: sw('butano', 120), o: [so(nm('butano', 120), ''), so(nm('butano', 300), ''), so(nm('butano', 180), ''), so(nm('butano', 0), '')], a: 0, e: 'Eclipsada CH₃/H (120°).' },
  { title: 'Direção', type: 'mc', struct: true, q: 'A conformação abaixo foi desenhada olhando C2 → C3. Qual é a mesma conformação vista de C3 → C2?', fig: nm('butano', 60), o: [so(nm('butano', 60, 'rev'), ''), so(nm('butano', 60), ''), so(nm('butano', 180, 'rev'), ''), so(nm('butano', 0, 'rev'), '')], a: 0, e: 'Troque frente/trás e espelhe.' },
  { title: '2-Metilbutano', type: 'mc', q: 'Na conformação alternada mais estável do 2-metilbutano (C2–C3), quantas interações gauche CH₃/CH₃ existem?', o: ['1', '0', '2', '3'], a: 0, e: 'Sempre há pelo menos uma (C2 tem dois CH₃).' },
  { title: '2,3-Dimetilbutano', type: 'mc', q: 'No 2,3-dimetilbutano (C2–C3), na conformação alternada em que os dois H estão anti, quantas interações gauche CH₃/CH₃ existem?', o: ['2', '4', '0', '1'], a: 0, e: 'Cada CH₃ da frente fica anti a um CH₃ de trás e gauche ao outro: 2 interações gauche. As outras duas alternadas têm 3, logo a conformação com os H anti é a mais estável.' },
  { title: 'Ponto no gráfico', type: 'mc', q: 'No perfil do butano, um mínimo local (não o global) corresponde a:', o: ['gauche', 'anti', 'eclipsada', 'totalmente eclipsada'], a: 0, e: '60° e 300°.' },
  { title: 'Ciclobutano', type: 'mc', q: 'O ciclobutano se dobra porque:', o: ['reduz o eclipsamento das ligações C–H (tensão torsional)', 'reduz a tensão angular', 'forma ligações π', 'aumenta a simetria'], a: 0, e: 'A dobra até aumenta um pouco a tensão angular.' },
  { title: 'Ciclopentano', type: 'mc', q: 'A conformação típica do ciclopentano é:', o: ['envelope (e meia-cadeira)', 'cadeira', 'plana', 'barco'], a: 0, e: 'Pseudorrotação rápida.' },
  { title: 'Barco', type: 'mc', q: 'O barco é menos estável que a cadeira principalmente por:', o: ['ligações eclipsadas e H de mastro próximos', 'tensão angular enorme', 'ligações π', 'ser plano'], a: 0, e: 'Torsional + estérica (flagpole).' },
  { title: 'Ordem de energia', type: 'order', q: 'Ordene as conformações do ciclo-hexano da <b>menor</b> para a <b>maior</b> energia.', items: [{ id: 'c', label: 'cadeira' }, { id: 't', label: 'barco torcido' }, { id: 'b', label: 'barco' }, { id: 'm', label: 'meia-cadeira' }], correct: ['c', 't', 'b', 'm'], top: 'menor', bottom: 'maior', explain: '0 < 23 < 29 < 45 kJ/mol (aprox.).' },
  { title: 'Flip correto', type: 'mc', struct: true, q: 'Qual estrutura representa o flip correto desta cadeira?', fig: ch({ '1u': 'CH3' }, 0), o: [so(ch({ '1u': 'CH3' }, 1), ''), so(ch({ '1d': 'CH3' }, 1), ''), so(ch({ '1d': 'CH3' }, 0), ''), so(ch({ '2u': 'CH3' }, 1), '')], a: 0, e: 'Axial up → equatorial up.' },
  { title: 'Posição em C3', type: 'mc', q: 'Um Br "up" em C3 (cadeira A, com C1 axial up) é:', o: ['axial', 'equatorial', 'depende do flip só', 'nenhum'], a: 0, e: 'C3 tem axial up (como C1 e C5).' },
  { title: 'Posição em C4', type: 'mc', q: 'Um OH "up" em C4 (cadeira A) é:', o: ['equatorial', 'axial', 'plano', 'nenhum'], a: 0, e: 'Em C4 o axial aponta para baixo.' },
  { title: 'Substituinte → posição', type: 'match', q: 'Na cadeira A (C1 axial up), associe.', pairs: [['C1 up', 'axial'], ['C2 up', 'equatorial'], ['C3 down', 'equatorial'], ['C4 down', 'axial']], e: 'Carbonos ímpares: axial up; pares: axial down.' },
  { title: 'Estrutura → cis/trans', type: 'match', q: 'Associe.', pairs: [['1u, 2u', 'cis-1,2'], ['1u, 3d', 'trans-1,3'], ['1u, 4d', 'trans-1,4'], ['1d, 4d', 'cis-1,4']], e: 'Mesma face = cis.' },
  { title: 'cis-1,3', type: 'mc', q: 'O cis-1,3-dimetilciclo-hexano interconverte entre:', o: ['(a,a) e (e,e)', '(a,e) e (e,a)', 'só (e,e)', 'só (a,a)'], a: 0, e: 'Prefere (e,e).' },
  { title: 'trans-1,2', type: 'mc', q: 'O trans-1,2-dimetilciclo-hexano interconverte entre:', o: ['(a,a) e (e,e)', '(a,e) e (e,a)', 'só (a,e)', 'nenhuma'], a: 0, e: 'Prefere (e,e).' },
  { title: 'cis-1,4', type: 'mc', q: 'O cis-1,4-dimetilciclo-hexano:', o: ['sempre tem um CH₃ axial', 'pode ser diequatorial', 'é sempre diaxial', 'não sofre flip'], a: 0, e: '(a,e) ⇌ (e,a), mesma energia.' },
  { title: 'Valores A', type: 'order', q: 'Ordene pela preferência equatorial (maior → menor).', items: [{ id: 't', label: 't-Bu' }, { id: 'i', label: 'i-Pr' }, { id: 'm', label: 'CH₃' }, { id: 'c', label: 'Cl' }], correct: ['t', 'i', 'm', 'c'], top: 'maior', bottom: 'menor', explain: '21 > 9,2 > 7,3 > 2,2 kJ/mol (aprox.).' },
];
const hard = [
  { title: 'Detecte o erro (1)', type: 'mc', q: 'Uma Newman mostra quatro ligações saindo do ponto central. Qual o erro?', o: ['o C da frente tem apenas três substituintes visíveis (a quarta ligação é a C–C, ao longo do olhar)', 'deveria haver dois pontos', 'falta o círculo de trás', 'não há erro'], a: 0, e: 'Carbono tetravalente: 3 + a ligação C–C.' },
  { title: 'Detecte o erro (2)', type: 'mc', q: 'Uma cadeira desenhada com um carbono ligado a 5 átomos. Qual o erro?', o: ['carbono pentavalente: cada C do anel tem 2 C + 2 substituintes', 'falta um H axial', 'deveria ser barco', 'não há erro'], a: 0, e: 'Valência 4.' },
  { title: 'Detecte o erro (3)', type: 'mc', q: '"No flip, o CH₃ axial up passou a equatorial down." Qual o erro?', o: ['up permanece up no flip', 'deveria continuar axial', 'o flip não muda nada', 'não há erro'], a: 0, e: 'Só axial ↔ equatorial.' },
  { title: 'Detecte o erro (4)', type: 'mc', q: '"cis-1,4-dimetil = os dois equatoriais." Qual o erro?', o: ['cis significa mesma face; no 1,4-cis um é axial e o outro equatorial', 'cis significa dois axiais', 'trans é que tem os dois equatoriais nunca', 'não há erro'], a: 0, e: 'cis/trans não é axial/equatorial.' },
  { title: 'Detecte o erro (5)', type: 'mc', q: 'Um desenho mostra o H axial de C2 apontando para cima, na mesma cadeira em que o de C1 também aponta para cima. Qual o erro?', o: ['os axiais alternam: se C1 é up, C2 é down', 'axiais são horizontais', 'C2 não tem axial', 'não há erro'], a: 0, e: 'Alternância axial.' },
  { title: 'Detecte o erro (6)', type: 'mc', q: 'O modelo 3D mostra o butano gauche, mas a Newman ao lado mostra os CH₃ a 180°. O problema é:', o: ['a projeção é incompatível com o modelo 3D', 'a Newman pode mostrar outra molécula', 'gauche e anti são iguais', 'não há erro'], a: 0, e: 'Newman é só um ponto de vista da MESMA conformação.' },
  { title: 'Flip e cis/trans', type: 'mc', struct: true, q: 'Qual cadeira é o trans-1,2-dimetilciclo-hexano diequatorial?', o: [so(ch({ '1u': 'CH3', '2d': 'CH3' }, 1), ''), so(ch({ '1u': 'CH3', '2u': 'CH3' }, 1), ''), so(ch({ '1u': 'CH3', '2d': 'CH3' }, 0), ''), so(ch({ '1u': 'CH3', '3u': 'CH3' }, 1), '')], a: 0, e: 'trans-1,2 (up/down) após o flip: (e,e).' },
  { title: 'Trava conformacional', type: 'mc', q: 'No trans-1-terc-butil-4-metilciclo-hexano:', o: ['t-Bu e CH₃ ambos equatoriais', 't-Bu axial, CH₃ equatorial', 'ambos axiais', 'as cadeiras têm a mesma energia'], a: 0, e: 'trans-1,4: (e,e) disponível e o t-Bu exige equatorial.' },
  { title: 'Grupos diferentes', type: 'mc', q: 'cis-1-isopropil-4-metil: qual grupo fica equatorial na cadeira principal?', o: ['isopropil', 'metil', 'ambos', 'nenhum'], a: 0, e: 'cis-1,4 é (a,e); o maior fica equatorial.' },
  { title: 'Grupos diferentes (2)', type: 'mc', q: 'trans-1-terc-butil-3-metil: na cadeira principal o CH₃ é:', o: ['axial', 'equatorial', 'eclipsado', 'anti'], a: 0, e: 'trans-1,3 é (a,e): t-Bu equatorial obriga CH₃ axial.' },
  { title: 'Energia', type: 'mc', q: 'Estime ΔE entre as cadeiras do cis-1-terc-butil-4-metilciclo-hexano (valores A: t-Bu 21; CH₃ 7,3 kJ/mol).', o: ['≈ 14 kJ/mol', '≈ 28 kJ/mol', '≈ 0', '≈ 7 kJ/mol'], a: 0, e: '21 − 7,3 ≈ 14 kJ/mol.' },
  { title: 'Ciclo-hexanol', type: 'mc', q: 'trans-4-terc-butilciclo-hexanol: o OH está', o: ['equatorial', 'axial', 'em barco', 'eclipsado'], a: 0, e: 'trans-1,4 com t-Bu equatorial → (e,e).' },
  { title: 'Rotação e quiralidade', type: 'tf', q: 'Sobre o butano:', items: [['As duas gauche são imagens especulares.', 'V'], ['O butano gauche pode ser isolado como enantiômero à temperatura ambiente.', 'F'], ['A anti tem plano de simetria.', 'V']], e: 'Rotação rápida interconverte as gauche.' },
  { title: 'Fração anti', type: 'mc', q: 'Sabendo que gauche está ≈ 3,8 kJ/mol acima da anti e que existem 2 gauche, a fração aproximada de anti a 25 °C é:', o: ['≈ 70%', '≈ 50%', '≈ 95%', '≈ 33%'], a: 0, e: 'K(gauche/anti) ≈ 2·e^(−3,8/2,48) ≈ 0,43 → anti ≈ 1/1,43 ≈ 70%.' },
  { title: 'Integração', type: 'mc', q: 'Qual afirmação é correta?', o: ['A inversão de cadeira passa pela meia-cadeira (máximo de energia) e pelo barco torcido (mínimo local)', 'O barco é um mínimo global', 'A meia-cadeira é um intermediário estável', 'O flip exige quebra de ligações'], a: 0, e: 'Veja o perfil de energia no módulo Inversão.' },
];
export const PROPOSED = { easy, mid, hard };
